/* @Codex */
// Closed, pure 0.8.5 catalog admission seam. C1 owns source materialization.
import { FABRIC_VENUES, EGRESS_PROFILES, type FabricVenue } from './contract';

export const CANONICAL_APPLICATION_CATALOG_SCHEMA = 'mediflow.canonical-application-catalog.v1' as const;
export type CanonicalApplicationCatalog = Readonly<{ schema: typeof CANONICAL_APPLICATION_CATALOG_SCHEMA; catalogRevision: number; applyPolicy: 'none'; entries: readonly Readonly<Record<string, unknown>>[] }>;

export class CanonicalApplicationCatalogError extends Error {
    constructor(message: string) { super(`Canonical application catalog rejected: ${message}`); this.name = 'CanonicalApplicationCatalogError'; }
}

const ROW_COUNT = 66;
const CAPABILITY_ID = /^[a-z][a-z0-9]*(?:[._/-][a-z0-9]+)*$/;
const SCHEMA_ID = /^[a-z][a-z0-9]*(?:[._/-][a-z0-9]+)*\.v[1-9][0-9]*$/;
const SEMVER = /^(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)$/;
const TOP_LEVEL_KEYS = ['schema', 'catalogRevision', 'applyPolicy', 'entries'];
const ROW_KEYS = ['sourceRow', 'capabilityId', 'capabilityVersion', 'rowRevision', 'lifecycle', 'implementation', 'input', 'output', 'mode', 'maxStage', 'dataContext', 'authority', 'idempotency', 'conflict', 'fabricDependency', 'execution', 'venues', 'egress', 'offline', 'headlessDisposition', 'evidence', 'uiSurfaces'];
const STAGES = ['none', 'observe', 'read', 'compute', 'propose', 'preview'] as const;
const DISPOSITIONS = ['available', 'proposal_only', 'manual_only', 'unavailable'] as const;
const VENUES = new Set<string>(FABRIC_VENUES);
const PROVIDERS = new Set(['ollama', 'athena_mlx', 'in_house']);
const EGRESS = new Set(Object.values(EGRESS_PROFILES).map(({ egress }) => egress));

function fail(message: string): never { throw new CanonicalApplicationCatalogError(message); }
function record(value: unknown, label: string): Record<string, unknown> { if (typeof value !== 'object' || value === null || Array.isArray(value) || ![Object.prototype, null].includes(Object.getPrototypeOf(value))) fail(`${label} must be a plain object`); return value as Record<string, unknown>; }
function exactKeys(value: Record<string, unknown>, keys: readonly string[], label: string): void { if (Object.keys(value).length !== keys.length || keys.some((key) => !Object.hasOwn(value, key))) fail(`${label} has missing or unknown fields`); }
function oneOf<T extends string>(value: unknown, values: readonly T[], label: string): T { if (typeof value !== 'string' || !values.includes(value as T)) fail(`${label} is invalid`); return value as T; }
function positive(value: unknown, label: string): number { if (!Number.isSafeInteger(value) || (value as number) < 1) fail(`${label} must be a positive safe integer`); return value as number; }
function text(value: unknown, pattern: RegExp, label: string): string { if (typeof value !== 'string' || !pattern.test(value)) fail(`${label} is invalid`); return value; }
function strings(value: unknown, label: string, allowEmpty = false): readonly string[] { if (!Array.isArray(value) || (!allowEmpty && value.length === 0) || Object.keys(value).length !== value.length || !value.every((item) => typeof item === 'string' && item.length > 0) || new Set(value).size !== value.length) fail(`${label} must be a unique text array`); return value; }
function schema(value: unknown, label: string): void { const item = record(value, label); if (item.kind === 'none') { exactKeys(item, ['kind'], label); return; } exactKeys(item, ['kind', 'schemaId'], label); if (item.kind !== 'json_schema') fail(`${label}.kind is invalid`); text(item.schemaId, SCHEMA_ID, `${label}.schemaId`); }
function evidence(value: unknown, label: string): readonly Record<string, unknown>[] {
    if (!Array.isArray(value) || Object.keys(value).length !== value.length) fail(`${label} must be an array`);
    return value.map((item, index) => { const entry = record(item, `${label}[${index}]`); exactKeys(entry, ['kind', 'ref', 'supports', 'polarity'], `${label}[${index}]`); oneOf(entry.kind, ['source_row', 'accepted_adr', 'code_contract', 'automated_test', 'synthetic_runtime', 'manual_verification'], `${label}[${index}].kind`); if (typeof entry.ref !== 'string' || !/^[\x20-\x7e]{1,256}$/.test(entry.ref)) fail(`${label}[${index}].ref is invalid`); oneOf(entry.polarity, ['supports', 'contradicts'], `${label}[${index}].polarity`); for (const pointer of strings(entry.supports, `${label}[${index}].supports`)) if (!/^(?:\/(?:[^~/]|~[01])*)+$/.test(pointer)) fail(`${label}[${index}].supports is invalid`); return entry; });
}
function supported(entries: readonly Record<string, unknown>[], pointer: string): boolean { const matching = entries.filter((entry) => (entry.supports as readonly string[]).includes(pointer)); return matching.some((entry) => entry.polarity === 'supports') && !matching.some((entry) => entry.polarity === 'contradicts'); }
function requiresEvidence(entries: readonly Record<string, unknown>[], pointer: string, permissive: boolean): void { if (permissive && !supported(entries, pointer)) fail(`${pointer} requires direct supporting evidence`); }
function copyFreeze(value: unknown): unknown { if (Array.isArray(value)) return Object.freeze(value.map(copyFreeze)); if (typeof value === 'object' && value !== null) return Object.freeze(Object.fromEntries(Object.entries(value).map(([key, child]) => [key, copyFreeze(child)]))); return value; }

function validateRow(value: unknown, index: number): Readonly<Record<string, unknown>> {
    const row = record(value, `entries[${index}]`); exactKeys(row, ROW_KEYS, `entries[${index}]`);
    if (positive(row.sourceRow, `entries[${index}].sourceRow`) !== index + 1) fail(`entries[${index}].sourceRow must be sequential`);
    text(row.capabilityId, CAPABILITY_ID, `entries[${index}].capabilityId`); text(row.capabilityVersion, SEMVER, `entries[${index}].capabilityVersion`); positive(row.rowRevision, `entries[${index}].rowRevision`);
    const lifecycle = oneOf(row.lifecycle, ['active', 'deprecated', 'retired', 'unresolved'], `entries[${index}].lifecycle`);
    const implementation = oneOf(row.implementation, ['available', 'proposal_only', 'manual_only', 'unavailable', 'unresolved'], `entries[${index}].implementation`);
    schema(row.input, `entries[${index}].input`); schema(row.output, `entries[${index}].output`);
    const mode = oneOf(row.mode, ['deterministic', 'generative', 'hybrid', 'manual', 'unresolved'], `entries[${index}].mode`);
    const maxStage = oneOf(row.maxStage, STAGES, `entries[${index}].maxStage`);
    const context = record(row.dataContext, `entries[${index}].dataContext`); exactKeys(context, ['kind', 'freshness', 'retention'], `entries[${index}].dataContext`); oneOf(context.kind, ['none', 'session_nonclinical', 'patient_opaque', 'patient_minimized_projection', 'patient_document_handle', 'aggregate_nonidentifying', 'administrative_nonclinical', 'unresolved'], `entries[${index}].dataContext.kind`); oneOf(context.freshness, ['none', 'selection_epoch', 'source_revision', 'selection_epoch_and_source_revision', 'unresolved'], `entries[${index}].dataContext.freshness`); oneOf(context.retention, ['none', 'ephemeral', 'durable_review', 'unresolved'], `entries[${index}].dataContext.retention`);
    const authority = record(row.authority, `entries[${index}].authority`); exactKeys(authority, ['read', 'preview', 'proposal', 'reviewDecision', 'apply'], `entries[${index}].authority`); for (const key of ['read', 'preview', 'proposal'] as const) oneOf(authority[key], ['denied', 'authenticated_session', 'session_owner', 'physician_interactive'], `entries[${index}].authority.${key}`); oneOf(authority.reviewDecision, ['not_applicable', 'physician_interactive'], `entries[${index}].authority.reviewDecision`); if (authority.apply !== 'denied') fail(`entries[${index}].authority.apply must be denied`);
    const idempotency = record(row.idempotency, `entries[${index}].idempotency`); exactKeys(idempotency, ['policy', 'scope', 'replay'], `entries[${index}].idempotency`); oneOf(idempotency.policy, ['not_applicable', 'request_key', 'unresolved'], `entries[${index}].idempotency.policy`); oneOf(idempotency.scope, ['not_applicable', 'capability_session', 'review_record', 'unresolved'], `entries[${index}].idempotency.scope`); oneOf(idempotency.replay, ['not_applicable', 'same_request_same_result', 'unresolved'], `entries[${index}].idempotency.replay`);
    const conflict = record(row.conflict, `entries[${index}].conflict`); exactKeys(conflict, ['revisionKind', 'expectedRevision', 'staleDisposition'], `entries[${index}].conflict`); const revisionKind = oneOf(conflict.revisionKind, ['none', 'selection_epoch', 'source_revision', 'review_revision', 'unresolved'], `entries[${index}].conflict.revisionKind`); const expectedRevision = oneOf(conflict.expectedRevision, ['forbidden', 'required', 'unresolved'], `entries[${index}].conflict.expectedRevision`); const staleDisposition = oneOf(conflict.staleDisposition, ['not_applicable', 'deny_conflict', 'unresolved'], `entries[${index}].conflict.staleDisposition`); if (revisionKind !== 'none' && revisionKind !== 'unresolved' && (expectedRevision !== 'required' || staleDisposition !== 'deny_conflict')) fail(`entries[${index}].conflict must deny stale revisions`);
    const fabric = record(row.fabricDependency, `entries[${index}].fabricDependency`); exactKeys(fabric, ['broker', 'providers', 'selection', 'readiness', 'receipt', 'provenance', 'fallback'], `entries[${index}].fabricDependency`); oneOf(fabric.broker, ['none', 'dedicated_capability_broker', 'unresolved'], `entries[${index}].fabricDependency.broker`); for (const provider of strings(fabric.providers, `entries[${index}].fabricDependency.providers`, true)) if (!PROVIDERS.has(provider)) fail(`entries[${index}].fabricDependency.providers is invalid`); oneOf(fabric.selection, ['not_applicable', 'fixed_explicit', 'caller_explicit', 'unresolved'], `entries[${index}].fabricDependency.selection`); for (const key of ['readiness', 'receipt', 'provenance'] as const) oneOf(fabric[key], ['not_applicable', 'required', 'unresolved'], `entries[${index}].fabricDependency.${key}`); if (fabric.fallback !== 'forbidden') fail(`entries[${index}].fabricDependency.fallback must be forbidden`);
    const execution = record(row.execution, `entries[${index}].execution`); exactKeys(execution, ['kind', 'cancel', 'revoke', 'rateLimit'], `entries[${index}].execution`); const executionKind = oneOf(execution.kind, ['sync', 'in_process_job', 'manual', 'unresolved'], `entries[${index}].execution.kind`); const cancel = oneOf(execution.cancel, ['not_applicable', 'initiating_session', 'unresolved'], `entries[${index}].execution.cancel`); const revoke = oneOf(execution.revoke, ['not_applicable', 'host_on_session_or_lease_end', 'unresolved'], `entries[${index}].execution.revoke`); const rateLimit = record(execution.rateLimit, `entries[${index}].execution.rateLimit`); const rateLimitKind = oneOf(rateLimit.kind, ['deny', 'single_flight', 'fixed_window'], `entries[${index}].execution.rateLimit.kind`); if (rateLimitKind === 'deny') exactKeys(rateLimit, ['kind'], `entries[${index}].execution.rateLimit`); else if (rateLimitKind === 'single_flight') { exactKeys(rateLimit, ['kind', 'scope'], `entries[${index}].execution.rateLimit`); if (rateLimit.scope !== 'capability_session') fail(`entries[${index}].execution.rateLimit.scope is invalid`); } else { exactKeys(rateLimit, ['kind', 'scope', 'limit', 'windowSeconds'], `entries[${index}].execution.rateLimit`); if (rateLimit.scope !== 'capability_session') fail(`entries[${index}].execution.rateLimit.scope is invalid`); const limit = positive(rateLimit.limit, `entries[${index}].execution.rateLimit.limit`); const seconds = positive(rateLimit.windowSeconds, `entries[${index}].execution.rateLimit.windowSeconds`); if (limit > 1000 || seconds > 86400) fail(`entries[${index}].execution.rateLimit is out of range`); }
    const venues = strings(row.venues, `entries[${index}].venues`); if (!venues.every((venue): venue is FabricVenue => VENUES.has(venue))) fail(`entries[${index}].venues is invalid`); if (!EGRESS.has(row.egress as never) || row.egress !== 'none') fail(`entries[${index}].egress must be none`); oneOf(row.offline, ['required', 'not_applicable', 'unresolved'], `entries[${index}].offline`);
    const disposition = oneOf(row.headlessDisposition, DISPOSITIONS, `entries[${index}].headlessDisposition`); const surfaces = strings(row.uiSurfaces, `entries[${index}].uiSurfaces`); if (!surfaces.every((surface) => ['none', 'web_card', 'web_detail', 'review_queue', 'review_detail', 'job_status', 'provider_selector', 'manual_host', 'headless_api'].includes(surface)) || (surfaces.includes('none') && surfaces.length !== 1)) fail(`entries[${index}].uiSurfaces is invalid`);
    if (maxStage === 'propose' && disposition !== 'proposal_only') fail(`entries[${index}].propose must be proposal_only`); if (disposition === 'proposal_only' && (maxStage !== 'propose' || (row.input as Record<string, unknown>).kind !== 'json_schema' || (row.output as Record<string, unknown>).kind !== 'json_schema' || authority.proposal === 'denied' || authority.reviewDecision !== 'physician_interactive' || !surfaces.includes('headless_api') || !surfaces.includes('review_queue') || !surfaces.includes('review_detail'))) fail(`entries[${index}].proposal_only is incomplete`); if (disposition === 'available' && !['read', 'preview'].includes(maxStage)) fail(`entries[${index}].available must be read or preview`); if ((disposition === 'manual_only' || disposition === 'unavailable') && maxStage !== 'none') fail(`entries[${index}].non-headless row must have maxStage none`); if (mode === 'manual' && disposition !== 'manual_only') fail(`entries[${index}].manual mode must be manual_only`); if (executionKind === 'in_process_job' && (idempotency.policy !== 'request_key' || idempotency.replay !== 'same_request_same_result' || cancel !== 'initiating_session' || revoke !== 'host_on_session_or_lease_end' || rateLimitKind === 'deny')) fail(`entries[${index}].job control is incomplete`);
    const entries = evidence(row.evidence, `entries[${index}].evidence`);
    requiresEvidence(entries, '/lifecycle', lifecycle !== 'unresolved'); requiresEvidence(entries, '/implementation', implementation !== 'unavailable' && implementation !== 'unresolved'); requiresEvidence(entries, '/input', (row.input as Record<string, unknown>).kind !== 'none'); requiresEvidence(entries, '/output', (row.output as Record<string, unknown>).kind !== 'none'); requiresEvidence(entries, '/mode', mode !== 'unresolved'); requiresEvidence(entries, '/maxStage', maxStage !== 'none'); requiresEvidence(entries, '/headlessDisposition', disposition !== 'unavailable'); for (const key of ['kind', 'freshness', 'retention'] as const) requiresEvidence(entries, `/dataContext/${key}`, context[key] !== 'unresolved'); for (const key of ['policy', 'scope', 'replay'] as const) requiresEvidence(entries, `/idempotency/${key}`, idempotency[key] !== 'unresolved'); for (const key of ['revisionKind', 'expectedRevision', 'staleDisposition'] as const) requiresEvidence(entries, `/conflict/${key}`, conflict[key] !== 'unresolved'); requiresEvidence(entries, '/fabricDependency/broker', fabric.broker !== 'unresolved'); requiresEvidence(entries, '/fabricDependency/providers', (fabric.providers as readonly unknown[]).length > 0); requiresEvidence(entries, '/fabricDependency/selection', fabric.selection !== 'unresolved'); for (const key of ['readiness', 'receipt', 'provenance'] as const) requiresEvidence(entries, `/fabricDependency/${key}`, fabric[key] !== 'unresolved'); requiresEvidence(entries, '/execution/kind', executionKind !== 'unresolved'); requiresEvidence(entries, '/execution/cancel', cancel !== 'unresolved'); requiresEvidence(entries, '/execution/revoke', revoke !== 'unresolved'); requiresEvidence(entries, '/execution/rateLimit', rateLimitKind !== 'deny'); requiresEvidence(entries, '/offline', row.offline !== 'unresolved'); requiresEvidence(entries, '/uiSurfaces', !surfaces.includes('none'));
    for (const key of ['read', 'preview', 'proposal'] as const) requiresEvidence(entries, `/authority/${key}`, authority[key] !== 'denied'); requiresEvidence(entries, '/authority/reviewDecision', authority.reviewDecision !== 'not_applicable');
    return copyFreeze(row) as Readonly<Record<string, unknown>>;
}

export function snapshotCanonicalApplicationCatalog(value: unknown): CanonicalApplicationCatalog {
    const catalog = record(value, 'catalog'); exactKeys(catalog, TOP_LEVEL_KEYS, 'catalog'); if (catalog.schema !== CANONICAL_APPLICATION_CATALOG_SCHEMA) fail('catalog.schema is invalid'); positive(catalog.catalogRevision, 'catalog.catalogRevision'); if (catalog.applyPolicy !== 'none') fail('catalog.applyPolicy must be none'); if (!Array.isArray(catalog.entries) || catalog.entries.length !== ROW_COUNT || Object.keys(catalog.entries).length !== ROW_COUNT) fail('catalog.entries must contain exactly 66 rows');
    const entries = catalog.entries.map(validateRow); const identifiers = new Set(entries.map((entry) => entry.capabilityId)); if (identifiers.size !== ROW_COUNT) fail('catalog.entries has duplicate capabilityId values'); return Object.freeze({ schema: CANONICAL_APPLICATION_CATALOG_SCHEMA, catalogRevision: catalog.catalogRevision as number, applyPolicy: 'none', entries: Object.freeze(entries) });
}
