/* @Codex */
import type {
    DeterministicCapabilityId,
    FabricCapabilityDescriptor,
    FabricVenue,
} from './contract';

const LOCAL_DETERMINISTIC_VENUES: readonly FabricVenue[] = Object.freeze([
    'local_process',
    'home_base',
] as const);

export const DETERMINISTIC_CAPABILITY_DESCRIPTORS: Readonly<
    Record<DeterministicCapabilityId, FabricCapabilityDescriptor>
> = Object.freeze({
    icd_lookup: Object.freeze({
        id: 'icd_lookup',
        class: 'deterministic',
        operation: 'lookup',
        authorityPlane: 'clinical_application',
        dataClass: 'clinical',
        venues: LOCAL_DETERMINISTIC_VENUES,
        egressProfileId: 'local_only',
        review: 'review_first',
        availabilityDisposition: 'available',
        killSwitch: null,
        contractSchema: null,
        entryPoint: 'lib/icd-service.ts',
    }),
    aifa_drug_search: Object.freeze({
        id: 'aifa_drug_search',
        class: 'deterministic',
        operation: 'lookup',
        authorityPlane: 'clinical_application',
        dataClass: 'clinical',
        venues: LOCAL_DETERMINISTIC_VENUES,
        egressProfileId: 'local_only',
        review: 'review_first',
        availabilityDisposition: 'available',
        killSwitch: null,
        contractSchema: 'mediflow.aifa-catalog-manifest.v1',
        entryPoint: 'lib/aifa-catalog.ts',
    }),
    service_prescription_matching: Object.freeze({
        id: 'service_prescription_matching',
        class: 'deterministic',
        operation: 'matching',
        authorityPlane: 'clinical_application',
        dataClass: 'clinical',
        venues: LOCAL_DETERMINISTIC_VENUES,
        egressProfileId: 'local_only',
        review: 'review_first',
        availabilityDisposition: 'available',
        killSwitch: null,
        contractSchema: null,
        entryPoint: 'lib/service-prescription-write.ts',
    }),
    evidence_absorption: Object.freeze({
        id: 'evidence_absorption',
        class: 'deterministic',
        operation: 'extraction',
        authorityPlane: 'clinical_application',
        dataClass: 'clinical',
        venues: LOCAL_DETERMINISTIC_VENUES,
        egressProfileId: 'local_only',
        review: 'review_first',
        availabilityDisposition: 'available',
        killSwitch: null,
        contractSchema: 'mediflow.evidence_queue.v1',
        entryPoint: 'lib/domain/documents/evidence-queue-contract.ts',
    }),
    patient_open_loops: Object.freeze({
        id: 'patient_open_loops',
        class: 'deterministic',
        operation: 'projection',
        authorityPlane: 'clinical_application',
        dataClass: 'clinical',
        venues: LOCAL_DETERMINISTIC_VENUES,
        egressProfileId: 'local_only',
        review: 'informational',
        availabilityDisposition: 'available',
        killSwitch: null,
        contractSchema: null,
        entryPoint: 'lib/patient-open-loops.ts',
    }),
    fhir_export: Object.freeze({
        id: 'fhir_export',
        class: 'deterministic',
        operation: 'export',
        authorityPlane: 'clinical_application',
        dataClass: 'clinical',
        venues: LOCAL_DETERMINISTIC_VENUES,
        egressProfileId: 'local_only',
        review: 'informational',
        availabilityDisposition: 'available',
        killSwitch: null,
        contractSchema: null,
        entryPoint: 'lib/fhir/bundle-generator.ts',
    }),
    document_classification: Object.freeze({
        id: 'document_classification',
        class: 'deterministic',
        operation: 'classification',
        authorityPlane: 'clinical_application',
        dataClass: 'clinical',
        venues: LOCAL_DETERMINISTIC_VENUES,
        egressProfileId: 'local_only',
        review: 'review_first',
        availabilityDisposition: 'available',
        killSwitch: null,
        contractSchema: null,
        entryPoint: 'lib/domain/documents/document-class-router.ts',
    }),
    document_identity_resolution: Object.freeze({
        id: 'document_identity_resolution',
        class: 'deterministic',
        operation: 'extraction',
        authorityPlane: 'clinical_application',
        dataClass: 'clinical',
        venues: LOCAL_DETERMINISTIC_VENUES,
        egressProfileId: 'local_only',
        review: 'review_first',
        availabilityDisposition: 'available',
        killSwitch: null,
        contractSchema: null,
        entryPoint: 'lib/domain/documents/document-identity-resolution.ts',
    }),
    pii_redaction_layer1: Object.freeze({
        id: 'pii_redaction_layer1',
        class: 'deterministic',
        operation: 'redaction',
        authorityPlane: 'clinical_application',
        dataClass: 'clinical',
        venues: LOCAL_DETERMINISTIC_VENUES,
        egressProfileId: 'local_only',
        review: 'informational',
        availabilityDisposition: 'available',
        killSwitch: null,
        contractSchema: null,
        entryPoint: 'lib/ai-egress-gate.ts',
    }),
    fse_document_validation: Object.freeze({
        id: 'fse_document_validation',
        class: 'deterministic',
        operation: 'validation',
        authorityPlane: 'clinical_application',
        dataClass: 'clinical',
        venues: LOCAL_DETERMINISTIC_VENUES,
        egressProfileId: 'local_only',
        review: 'informational',
        availabilityDisposition: 'available',
        killSwitch: null,
        contractSchema: null,
        entryPoint: 'lib/fse-validate-document.ts',
    }),
    observation_range_classification: Object.freeze({
        id: 'observation_range_classification',
        class: 'deterministic',
        operation: 'classification',
        authorityPlane: 'clinical_application',
        dataClass: 'clinical',
        venues: LOCAL_DETERMINISTIC_VENUES,
        egressProfileId: 'local_only',
        review: 'informational',
        availabilityDisposition: 'available',
        killSwitch: null,
        contractSchema: null,
        entryPoint: 'lib/observation-range.ts',
    }),
});
