/* @Codex */
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { afterEach, test } from 'node:test';

import { OllamaProviderAdapter } from '../ollama.ts';
import { admitDocumentSynthesisFabric, beginDocumentSynthesisFabricExecution } from './document-synthesis-fabric-admission.ts';
import { cancelDocumentSynthesisFabricExecutionPrepare, disposeDocumentSynthesisFabricPreparedExecution, finalizeDocumentSynthesisFabricPreparedExecution, prepareDocumentSynthesisFabricExecution, setDocumentSynthesisFabricExecutionPrepareTimeoutForTest } from './document-synthesis-fabric-execution-prepare.ts';
import { createDocumentSynthesisProviderBindingForTest } from './document-synthesis-provider-binding.ts';
import { captureDocumentSynthesisSourceSet } from './document-synthesis-source-set-contract.ts';
import { createDocumentSynthesisSourceSetCurrentnessOwner } from './document-synthesis-source-set-currentness-owner.ts';
import { createServerSessionProjectionOwnerRegistry } from '../../security/server-session-projection-owner.ts';
import { clearAllSessions, createSession } from '../../security/server-session.ts';

const SETTINGS = Object.freeze({ aiProvider: 'ollama', aiModel_reasoning: 'reasoning-local', aiUrl: 'http://localhost:11434' }); const ATTESTATION = Object.freeze({ authorityPlane: 'clinical_application', provider: 'ollama', executionMode: 'local', endpointClass: 'loopback', requestedModel: 'reasoning-local', canonicalModel: 'reasoning-local:latest', digest: 'sha256:synthetic', serverVersion: '0.32.5', checkedAt: '2026-08-25T12:00:00.000Z' }); const USER = Object.freeze({ id: ['synthetic', 'ds', 'prepare', 'user'].join('.'), username: ['synthetic', 'ds', 'prepare', 'clinician'].join('.'), role: 'clinician' as const }); const PAIR = Object.freeze({ patientId: 'patient.synthetic.ds.prepare', ambulatoryId: 'ambulatory.synthetic.ds.prepare' });
afterEach(() => clearAllSessions());
function body(text = 'Synthetic source.') { const digest = createHash('sha256').update(new TextEncoder().encode(text)).digest('hex'); return JSON.stringify({ output: { schemaVersion: 'mediflow.ai.extract.v1', task: 'document_synthesis', summary: 'Synthetic summary', data: { qualityLevel: 'green', medications: [], diagnoses: [], problemStatements: [], therapyCandidates: [], servicePrescriptions: [] } }, citations: [{ label: 'S1', quote: text, startByte: 0, endByte: new TextEncoder().encode(text).length, quoteSha256: digest }], claims: [{ claimPath: 'summary', labels: ['S1'] }, { claimPath: 'data.qualityLevel', labels: ['S1'] }] }); }
async function handoff(chat: OllamaProviderAdapter['chat'], clock: () => number = () => 1_000) { const original = OllamaProviderAdapter.prototype.chat; OllamaProviderAdapter.prototype.chat = chat; let entropy = 0; const registry = createServerSessionProjectionOwnerRegistry({ clock, entropy: () => Uint8Array.from({ length: 16 }, (_, index) => (entropy += 1) + index), resolve: (_session, pair) => Object.freeze({ ...pair }) }); const session = createSession(USER, 'web'); const owner = registry.acquire(session); owner.issueSelection({ expectedEpoch: 0, ...PAIR }); const captured = captureDocumentSynthesisSourceSet({ sourceSetEpoch: BigInt(3), revocationGeneration: BigInt(5), sources: [{ documentSourceRef: 'document.synthetic.ds.prepare', documentRevision: BigInt(7), documentFreshnessEpoch: BigInt(11), sourceText: 'Synthetic source.' }] }); assert.equal(captured.status, 'available'); if (captured.status !== 'available') throw new Error('source'); const capsule = createDocumentSynthesisSourceSetCurrentnessOwner(Object.freeze({ owner, session, sourceSet: captured.sourceSet })); const binding = await createDocumentSynthesisProviderBindingForTest({ readSettings: async () => SETTINGS, attest: async () => ATTESTATION }).bind(); assert.equal(binding.status, 'available'); if (binding.status !== 'available') throw new Error('binding'); const admitted = admitDocumentSynthesisFabric(Object.freeze({ owner, session, capsule, providerToken: binding.token })); assert.equal(admitted.status, 'available'); const value = admitted.token && beginDocumentSynthesisFabricExecution(admitted.token); assert.ok(value); return { value, restore() { OllamaProviderAdapter.prototype.chat = original; } }; }
function exact(result: Awaited<ReturnType<typeof prepareDocumentSynthesisFabricExecution>>, code: string) { assert.deepEqual({ ...result }, { status: 'denied', code, preparedToken: null, reviewOnly: true, writesPerformed: 0, applyPolicy: 'none', fallback: 'denied_by_contract' }); }

test('prepares one fixed lease-bound prompt with no output leakage or finalization', { concurrency: false }, async () => { const calls: unknown[][] = []; const fixture = await handoff(async (...args) => { calls.push(args); return { content: body(), stats: { latency: 0, tokensIn: 0, tokensOut: 0 } }; }); try { const result = await prepareDocumentSynthesisFabricExecution(fixture.value); assert.equal(result.status, 'available'); if (result.status !== 'available') return; const message = calls[0]?.[0] as Array<{ role: string; content: string }>; assert.equal(message.length, 1); assert.equal(message[0]?.role, 'user'); assert.equal(message[0]?.content.includes('Synthetic source.'), true); assert.equal(calls.length, 1); assert.equal(calls[0]?.[1] instanceof AbortSignal, true); assert.equal(calls[0]?.[2], 1400); assert.deepEqual(calls[0]?.[3], { responseFormat: 'json' }); assert.equal(Object.getPrototypeOf(result), null); assert.equal(Object.isFrozen(result), true); assert.deepEqual(Reflect.ownKeys(result), ['status', 'code', 'preparedToken', 'reviewOnly', 'writesPerformed', 'applyPolicy', 'fallback']); assert.deepEqual(Reflect.ownKeys(result.preparedToken), []); disposeDocumentSynthesisFabricPreparedExecution(result.preparedToken); } finally { fixture.restore(); } });

test('denies replay and hostile inputs without a second provider call', { concurrency: false }, async () => { let calls = 0; const fixture = await handoff(async () => { calls += 1; return { content: body(), stats: { latency: 0, tokensIn: 0, tokensOut: 0 } }; }); try { const first = prepareDocumentSynthesisFabricExecution(fixture.value); exact(await prepareDocumentSynthesisFabricExecution(fixture.value), 'canceled'); exact(await first, 'canceled'); assert.equal(calls, 1); for (const value of [{}, { ...fixture.value }, structuredClone(fixture.value), Object.freeze(Object.defineProperty({}, 'then', { value() {} }))]) exact(await prepareDocumentSynthesisFabricExecution(value), 'handoff_unavailable'); exact(await prepareDocumentSynthesisFabricExecution(new Proxy(fixture.value, {})), 'input_invalid'); } finally { fixture.restore(); } });

test('burns the handoff after timeout, malformed envelope, or source validation denial', { concurrency: false }, async () => { for (const [content, code] of [[null, 'response_invalid'], [body('Different synthetic source.'), 'validation_denied']] as const) { let calls = 0; const fixture = await handoff(async () => { calls += 1; return { content: content as string, stats: { latency: 0, tokensIn: 0, tokensOut: 0 } }; }); try { const result = await prepareDocumentSynthesisFabricExecution(fixture.value); exact(result, code); exact(await prepareDocumentSynthesisFabricExecution(fixture.value), 'handoff_unavailable'); assert.equal(calls, 1); } finally { fixture.restore(); } } });

test('aborts timeout or cancellation, burns the handoff, absorbs late rejection, and skips parse validation after return', { concurrency: false }, async () => { let rejectLate!: (reason: unknown) => void; const fixture = await handoff(async () => new Promise((_, reject) => { rejectLate = reject; })); const restore = setDocumentSynthesisFabricExecutionPrepareTimeoutForTest(0); const unhandled: unknown[] = []; const listener = (reason: unknown) => { unhandled.push(reason); }; process.on('unhandledRejection', listener); try { exact(await prepareDocumentSynthesisFabricExecution(fixture.value), 'provider_timeout'); exact(await prepareDocumentSynthesisFabricExecution(fixture.value), 'handoff_unavailable'); rejectLate(new Error('late')); await new Promise<void>((resolve) => setImmediate(resolve)); assert.deepEqual(unhandled, []); } finally { process.off('unhandledRejection', listener); restore?.(); fixture.restore(); } });

test('burns before direct finalization and returns only the private publication', { concurrency: false }, async () => { let calls = 0; const fixture = await handoff(async () => { calls += 1; return { content: body(), stats: { latency: 0, tokensIn: 0, tokensOut: 0 } }; }); try { const prepared = await prepareDocumentSynthesisFabricExecution(fixture.value); assert.equal(prepared.status, 'available'); if (prepared.status !== 'available') return; assert.equal(calls, 1); const publication = finalizeDocumentSynthesisFabricPreparedExecution(prepared.preparedToken); assert.ok(publication); assert.equal(calls, 1); assert.equal(Object.getPrototypeOf(publication), null); assert.equal(Object.isFrozen(publication), true); assert.deepEqual(Reflect.ownKeys(publication), ['schemaVersion', 'output', 'citations', 'claims', 'receipt', 'provenance']); assert.equal(Object.getPrototypeOf(publication.receipt), null); assert.equal(Object.isFrozen(publication.receipt), true); assert.deepEqual(Reflect.ownKeys(publication.receipt), ['schemaVersion', 'capability', 'outputSha256', 'claimCitationsDigestSha256', 'sourceSetDigestSha256', 'providerBindingReceipt', 'reviewOnly', 'applyPolicy', 'writesPerformed']); assert.equal(Object.getPrototypeOf(publication.provenance), null); assert.equal(Object.isFrozen(publication.provenance), true); assert.equal(finalizeDocumentSynthesisFabricPreparedExecution(prepared.preparedToken), null); disposeDocumentSynthesisFabricPreparedExecution(prepared.preparedToken); } finally { fixture.restore(); } });

test('burn makes nested finalization and disposal inert while exactly one commit succeeds', { concurrency: false }, async () => { let token: object | null = null; let armed = false; let reads = 0; let nested = 0; const fixture = await handoff(async () => ({ content: body(), stats: { latency: 0, tokensIn: 0, tokensOut: 0 } }), () => { if (armed && (reads += 1) === 3) { nested += 1; assert.equal(finalizeDocumentSynthesisFabricPreparedExecution(token), null); disposeDocumentSynthesisFabricPreparedExecution(token); } return 1_000; }); try { const prepared = await prepareDocumentSynthesisFabricExecution(fixture.value); assert.equal(prepared.status, 'available'); if (prepared.status !== 'available') return; token = prepared.preparedToken; armed = true; assert.ok(finalizeDocumentSynthesisFabricPreparedExecution(token)); assert.equal(nested, 1); const closedReads = reads; assert.equal(finalizeDocumentSynthesisFabricPreparedExecution(token), null); disposeDocumentSynthesisFabricPreparedExecution(token); assert.equal(reads, closedReads); } finally { fixture.restore(); } });

test('denies disposal-first and hostile finalizer tokens without reflection or deferred work', { concurrency: false }, async () => { const fixture = await handoff(async () => ({ content: body(), stats: { latency: 0, tokensIn: 0, tokensOut: 0 } })); let reads = 0; let traps = 0; const descriptor = Object.getOwnPropertyDescriptor(Object.prototype, 'then'); try { const prepared = await prepareDocumentSynthesisFabricExecution(fixture.value); assert.equal(prepared.status, 'available'); if (prepared.status !== 'available') return; disposeDocumentSynthesisFabricPreparedExecution(prepared.preparedToken); assert.equal(finalizeDocumentSynthesisFabricPreparedExecution(prepared.preparedToken), null); const accessor = Object.freeze(Object.defineProperty({}, 'token', { enumerable: true, get() { reads += 1; return prepared.preparedToken; } })); const proxy = new Proxy(prepared.preparedToken, { get() { traps += 1; throw new Error('trap'); } }); Object.defineProperty(Object.prototype, 'then', { configurable: true, get() { reads += 1; return undefined; } }); for (const value of [{}, { ...prepared.preparedToken }, structuredClone(prepared.preparedToken), accessor, proxy, Object.freeze({ then() {} }), Object.freeze({ evidence: Object.freeze({ receipt: 'forged' }) })]) assert.equal(finalizeDocumentSynthesisFabricPreparedExecution(value), null); assert.equal(reads, 0); assert.equal(traps, 0); await new Promise<void>((resolve) => setImmediate(resolve)); } finally { if (descriptor) Object.defineProperty(Object.prototype, 'then', descriptor); else delete (Object.prototype as { then?: unknown }).then; fixture.restore(); } });

test('uses captured finalizer intrinsics after post-import poison', { concurrency: false }, async () => { const fixture = await handoff(async () => ({ content: body(), stats: { latency: 0, tokensIn: 0, tokensOut: 0 } })); const get = WeakMap.prototype.get; const remove = WeakMap.prototype.delete; const apply = Reflect.apply; try { const prepared = await prepareDocumentSynthesisFabricExecution(fixture.value); assert.equal(prepared.status, 'available'); if (prepared.status !== 'available') return; WeakMap.prototype.get = () => { throw new Error('poisoned'); }; WeakMap.prototype.delete = () => { throw new Error('poisoned'); }; Reflect.apply = () => { throw new Error('poisoned'); }; assert.ok(finalizeDocumentSynthesisFabricPreparedExecution(prepared.preparedToken)); } finally { WeakMap.prototype.get = get; WeakMap.prototype.delete = remove; Reflect.apply = apply; fixture.restore(); } });

test('burns the prepared token before a literal tail call with no caller evidence', async () => { const source = await readFile('lib/ai-providers/fabric/document-synthesis-fabric-execution-prepare.ts', 'utf8'); const finalizer = source.match(/export function finalizeDocumentSynthesisFabricPreparedExecution[^\n]*/u)?.[0] ?? ''; assert.match(finalizer, /entry\.state = 'aborted'; ReflectApply\(WeakMapDelete, prepared, \[token\]\); return execution\.finalize\(\);/u); assert.doesNotMatch(finalizer, /catch|finally|Promise|frozen\(|JSON\.|structuredClone|callback|provenance|receipt/u); });

test('cancellation accepts only authentic active handoffs and burns the handoff', { concurrency: false }, async () => { let release!: () => void; const fixture = await handoff(async () => new Promise((resolve) => { release = () => resolve({ content: body(), stats: { latency: 0, tokensIn: 0, tokensOut: 0 } }); })); const unhandled: unknown[] = []; const listener = (reason: unknown) => { unhandled.push(reason); }; process.on('unhandledRejection', listener); try { const pending = prepareDocumentSynthesisFabricExecution(fixture.value); await new Promise<void>((resolve) => setImmediate(resolve)); cancelDocumentSynthesisFabricExecutionPrepare({}); cancelDocumentSynthesisFabricExecutionPrepare(new Proxy(fixture.value, {})); cancelDocumentSynthesisFabricExecutionPrepare(fixture.value); exact(await pending, 'canceled'); exact(await prepareDocumentSynthesisFabricExecution(fixture.value), 'handoff_unavailable'); release(); await new Promise<void>((resolve) => setImmediate(resolve)); assert.deepEqual(unhandled, []); } finally { process.off('unhandledRejection', listener); fixture.restore(); } });
