/* @Codex */
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { afterEach, test } from 'node:test';

import { OllamaProviderAdapter } from '../ollama.ts';
import { createDocumentSynthesisFabricProductionCompositionForTest } from './document-synthesis-fabric-production-composition.ts';
import { createDocumentSynthesisProviderBindingForTest } from './document-synthesis-provider-binding.ts';
import { captureDocumentSynthesisSourceSet } from './document-synthesis-source-set-contract.ts';
import { createDocumentSynthesisSourceSetCurrentnessOwner } from './document-synthesis-source-set-currentness-owner.ts';
import { createServerSessionProjectionOwnerRegistry } from '../../security/server-session-projection-owner.ts';
import { clearAllSessions, createSession } from '../../security/server-session.ts';

const SETTINGS = Object.freeze({ aiProvider: 'ollama', aiModel_reasoning: 'reasoning-local', aiUrl: 'http://localhost:11434' }); const ATTESTATION = Object.freeze({ authorityPlane: 'clinical_application', provider: 'ollama', executionMode: 'local', endpointClass: 'loopback', requestedModel: 'reasoning-local', canonicalModel: 'reasoning-local:latest', digest: 'sha256:synthetic', serverVersion: '0.32.5', checkedAt: '2026-08-25T12:00:00.000Z' }); const USER = Object.freeze({ id: ['synthetic', 'ds', 'production', 'user'].join('.'), username: ['synthetic', 'ds', 'production', 'clinician'].join('.'), role: 'clinician' as const }); const PAIR = Object.freeze({ patientId: 'patient.synthetic.ds.production', ambulatoryId: 'ambulatory.synthetic.ds.production' });
afterEach(() => clearAllSessions());
function body(text = 'Synthetic source.') { const quoteSha256 = createHash('sha256').update(new TextEncoder().encode(text)).digest('hex'); return JSON.stringify({ output: { schemaVersion: 'mediflow.ai.extract.v1', task: 'document_synthesis', summary: 'Synthetic summary', data: { qualityLevel: 'green', medications: [], diagnoses: [], problemStatements: [], therapyCandidates: [], servicePrescriptions: [] } }, citations: [{ label: 'S1', quote: text, startByte: 0, endByte: new TextEncoder().encode(text).length, quoteSha256 }], claims: [{ claimPath: 'summary', labels: ['S1'] }, { claimPath: 'data.qualityLevel', labels: ['S1'] }] }); }
async function fixture(chat: OllamaProviderAdapter['chat']) { const original = OllamaProviderAdapter.prototype.chat; OllamaProviderAdapter.prototype.chat = chat; let entropy = 0; const registry = createServerSessionProjectionOwnerRegistry({ clock: () => 1_000, entropy: () => Uint8Array.from({ length: 16 }, (_, index) => (entropy += 1) + index), resolve: (_session, pair) => Object.freeze({ ...pair, patientVersion: 1 }) }); const session = createSession(USER, 'web'); const owner = registry.acquire(session); owner.issueSelection({ expectedEpoch: 0, ...PAIR }); const captured = captureDocumentSynthesisSourceSet({ sourceSetEpoch: BigInt(3), revocationGeneration: BigInt(5), sources: [{ documentSourceRef: 'document.synthetic.ds.production', documentRevision: BigInt(7), documentFreshnessEpoch: BigInt(11), sourceText: 'Synthetic source.' }] }); assert.equal(captured.status, 'available'); if (captured.status !== 'available') throw new Error('source unavailable'); const capsule = createDocumentSynthesisSourceSetCurrentnessOwner(Object.freeze({ owner, session, sourceSet: captured.sourceSet })); const binding = createDocumentSynthesisProviderBindingForTest(Object.freeze({ readSettings: async () => SETTINGS, attest: async () => ATTESTATION })); return { configuration: Object.freeze({ owner, session, capsule }), binding, restore() { OllamaProviderAdapter.prototype.chat = original; } }; }

test('validates host configuration before binding and returns the exact private publication', { concurrency: false }, async () => { let binds = 0; const invalid = createDocumentSynthesisFabricProductionCompositionForTest(Object.freeze({}), Object.freeze({ bind: async () => { binds += 1; throw new Error('must not bind'); } })); assert.equal(invalid, null); assert.equal(binds, 0); let calls = 0; const value = await fixture(async () => { calls += 1; return { content: body(), stats: { latency: 0, tokensIn: 0, tokensOut: 0 } }; }); try { const composition = createDocumentSynthesisFabricProductionCompositionForTest(value.configuration, Object.freeze({ bind: async () => { binds += 1; return value.binding.bind(); } })); assert.ok(composition); assert.deepEqual(Reflect.ownKeys(composition), ['execute']); const publication = await composition.execute(); assert.ok(publication); assert.equal(binds, 1); assert.equal(calls, 1); assert.equal(Object.getPrototypeOf(publication), null); assert.equal(Object.isFrozen(publication), true); assert.deepEqual(Reflect.ownKeys(publication), ['schemaVersion', 'output', 'citations', 'claims', 'receipt', 'provenance']); assert.deepEqual(Reflect.ownKeys(publication.receipt), ['schemaVersion', 'capability', 'outputSha256', 'claimCitationsDigestSha256', 'sourceSetDigestSha256', 'providerBindingReceipt', 'reviewOnly', 'applyPolicy', 'writesPerformed']); assert.strictEqual(await composition.execute(), null); } finally { value.restore(); } });

test('allows exactly one terminal publication through replay and reentry', { concurrency: false }, async () => { let composition: ReturnType<typeof createDocumentSynthesisFabricProductionCompositionForTest> = null; let nested: unknown = undefined; let calls = 0; const value = await fixture(async () => { calls += 1; nested = await composition?.execute(); return { content: body(), stats: { latency: 0, tokensIn: 0, tokensOut: 0 } }; }); try { composition = createDocumentSynthesisFabricProductionCompositionForTest(value.configuration, Object.freeze({ bind: () => value.binding.bind() })); assert.ok(composition); const [publication, replay] = await Promise.all([composition.execute(), composition.execute()]); assert.ok(publication); assert.equal(replay, null); assert.equal(nested, null); assert.equal(calls, 1); } finally { value.restore(); } });

test('denies provider, abort, and hostile caller authority without work or deferred observation', { concurrency: false }, async () => { let binds = 0; const value = await fixture(async () => { throw new Error('must not invoke'); }); const dependencies = Object.freeze({ bind: async () => { binds += 1; return value.binding.bind(); } }); let reads = 0; let traps = 0; const unhandled: unknown[] = []; const listener = (reason: unknown) => { unhandled.push(reason); }; const descriptor = Object.getOwnPropertyDescriptor(Object.prototype, 'then'); process.on('unhandledRejection', listener); try { for (const input of [Object.freeze({ ...value.configuration, provider: 'forbidden' }), Object.freeze({ ...value.configuration, abort() {} }), Object.freeze(Object.defineProperty({ ...value.configuration }, 'owner', { enumerable: true, get() { reads += 1; return value.configuration.owner; } })), new Proxy(value.configuration, { get() { traps += 1; throw new Error('trap'); } }), Object.freeze({ ...value.configuration, then() {} })]) assert.equal(createDocumentSynthesisFabricProductionCompositionForTest(input, dependencies), null); Object.defineProperty(Object.prototype, 'then', { configurable: true, get() { reads += 1; return undefined; } }); assert.equal(createDocumentSynthesisFabricProductionCompositionForTest(Object.freeze({ evidence: 'forged' }), dependencies), null); assert.equal(binds, 0); assert.equal(reads, 0); assert.equal(traps, 0); await new Promise<void>((resolve) => setImmediate(resolve)); assert.deepEqual(unhandled, []); } finally { process.off('unhandledRejection', listener); if (descriptor) Object.defineProperty(Object.prototype, 'then', descriptor); else delete (Object.prototype as { then?: unknown }).then; value.restore(); } });

test('returns null for binding denial without exposing a receipt or terminal authority', { concurrency: false }, async () => { let calls = 0; const value = await fixture(async () => { calls += 1; throw new Error('must not invoke'); }); try { const composition = createDocumentSynthesisFabricProductionCompositionForTest(value.configuration, Object.freeze({ bind: async () => ({ status: 'denied' as const, code: 'settings_unavailable' as const, receipt: null, readiness: null, token: null }) })); assert.ok(composition); assert.equal(await composition.execute(), null); assert.equal(calls, 0); assert.equal(await composition.execute(), null); } finally { value.restore(); } });

test('does not expose the test binder outside Node test before dependency observation', { concurrency: false }, () => { const inherited: string[] = []; for (let index = 0; index < process.execArgv.length; index += 1) { const argument = process.execArgv[index]!; if (argument === '--test' || argument.startsWith('--test=') || argument.startsWith('--test-')) continue; inherited.push(argument); } const moduleUrl = new URL('./document-synthesis-fabric-production-composition.ts', import.meta.url).href; const program = `import { createDocumentSynthesisFabricProductionCompositionForTest as create } from ${JSON.stringify(moduleUrl)}; let reads = 0; let traps = 0; let binds = 0; let unhandled = 0; process.on('unhandledRejection', () => { unhandled += 1; }); const getter = Object.freeze(Object.defineProperty({}, 'bind', { enumerable: true, get() { reads += 1; return () => { binds += 1; return null; }; } })); const proxy = new Proxy(Object.freeze({ bind() { binds += 1; return null; } }), { get() { traps += 1; throw new Error('trap'); } }); const first = create(Object.freeze({}), getter); const second = create(Object.freeze({}), proxy); await new Promise((resolve) => setImmediate(resolve)); if (process.execArgv.some((argument) => argument === '--test' || argument.startsWith('--test=') || argument.startsWith('--test-')) || first !== null || second !== null || reads !== 0 || traps !== 0 || binds !== 0 || unhandled !== 0) process.exitCode = 1;`; const result = spawnSync(process.execPath, [...inherited, '--input-type=module', '--eval', program], { encoding: 'utf8' }); assert.equal(result.signal, null, result.stderr); assert.equal(result.status, 0, `${result.stdout}${result.stderr}`); });

test('keeps the production terminal path direct and excludes forbidden composition concerns', async () => { const source = await readFile('lib/ai-providers/fabric/document-synthesis-fabric-production-composition.ts', 'utf8'); assert.match(source, /const TEST_HARNESS = \(\(\) => \{ for \(let index = 0; index < ProcessExecArgvLength; index \+= 1\)[\s\S]*?if \(!TEST_HARNESS\) return null; const bind = testBinding\(dependencies\);/u); assert.match(source, /const prepared = await prepareDocumentSynthesisFabricExecution\(handoff\);[\s\S]*?state = 'terminal';\s*return finalizeDocumentSynthesisFabricPreparedExecution\(prepared\.preparedToken\);/u); assert.doesNotMatch(source, /\/api\/proxy\/ollama|legacy service|providerToken:.*input|prompt:.*input|route|database|persistence|apply|UI/u); const terminal = source.match(/state = 'terminal';\s*return finalizeDocumentSynthesisFabricPreparedExecution\(prepared\.preparedToken\);/u)?.[0] ?? ''; assert.doesNotMatch(terminal, /catch|finally|freeze|clone|dispose|serialize|lookup|Promise/u); });
