/* @Codex */
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { afterEach, test } from 'node:test';
import { types } from 'node:util';

import { admitDocumentSynthesisFabric, beginDocumentSynthesisFabricExecution, disposeDocumentSynthesisFabricAdmission, resolveDocumentSynthesisFabricExecutionHandoff } from './document-synthesis-fabric-admission.ts';
import { claimDocumentSynthesisProviderBindingForExecution, createDocumentSynthesisProviderBindingForTest, resolveDocumentSynthesisProviderBinding } from './document-synthesis-provider-binding.ts';
import { parseDocumentSynthesisProviderEnvelope } from './document-synthesis-provider-envelope.ts';
import { captureDocumentSynthesisSourceSet } from './document-synthesis-source-set-contract.ts';
import { createDocumentSynthesisSourceSetCurrentnessOwner } from './document-synthesis-source-set-currentness-owner.ts';
import { createServerSessionProjectionOwnerRegistry } from '../../security/server-session-projection-owner.ts';
import { clearAllSessions, createSession } from '../../security/server-session.ts';

const USER = { id: ['synthetic', 'fabric', 'admission', 'user'].join('.'), username: ['synthetic', 'fabric', 'admission', 'clinician'].join('.'), role: 'clinician' }; const PAIR = { patientId: 'patient.synthetic.fabric.admission', ambulatoryId: 'ambulatory.synthetic.fabric.admission' }; const SETTINGS = Object.freeze({ aiProvider: 'ollama', aiModel_reasoning: 'reasoning-local', aiUrl: 'http://localhost:11434' }); const ATTESTATION = Object.freeze({ authorityPlane: 'clinical_application', provider: 'ollama', executionMode: 'local', endpointClass: 'loopback', requestedModel: 'reasoning-local', canonicalModel: 'reasoning-local:latest', digest: 'sha256:synthetic', serverVersion: '0.32.5', checkedAt: '2026-08-25T12:00:00.000Z' });
afterEach(() => clearAllSessions());
function source(epoch = 3, text = 'Synthetic source.') { const result = captureDocumentSynthesisSourceSet({ sourceSetEpoch: BigInt(epoch), revocationGeneration: BigInt(5), sources: [{ documentSourceRef: 'document.synthetic.fabric.admission', documentRevision: BigInt(7), documentFreshnessEpoch: BigInt(11), sourceText: text }] }); assert.equal(result.status, 'available'); if (result.status !== 'available') throw new Error('synthetic source unavailable'); return result.sourceSet; }
function envelope(text = 'Synthetic source.') { const quoteSha256 = createHash('sha256').update(new TextEncoder().encode(text)).digest('hex'); const result = parseDocumentSynthesisProviderEnvelope({ content: JSON.stringify({ output: { schemaVersion: 'mediflow.ai.extract.v1', task: 'document_synthesis', summary: 'Synthetic summary', data: { qualityLevel: 'green', medications: [], diagnoses: [], problemStatements: [], therapyCandidates: [], servicePrescriptions: [] } }, citations: [{ label: 'S1', quote: text, startByte: 0, endByte: new TextEncoder().encode(text).length, quoteSha256 }], claims: [{ claimPath: 'summary', labels: ['S1'] }, { claimPath: 'data.qualityLevel', labels: ['S1'] }] }) }); assert.equal(result.status, 'available'); if (result.status !== 'available') throw new Error('synthetic envelope unavailable'); return result.token; }
function fixture(clock: () => number = () => 1_000) { let entropy = 0; const registry = createServerSessionProjectionOwnerRegistry({ clock, entropy: () => Uint8Array.from({ length: 16 }, (_, index) => (entropy += 1) + index), resolve: (_session, pair) => Object.freeze({ ...pair }) }); const session = createSession(USER, 'web'); const owner = registry.acquire(session); owner.issueSelection({ expectedEpoch: 0, ...PAIR }); const capsule = createDocumentSynthesisSourceSetCurrentnessOwner(Object.freeze({ owner, session, sourceSet: source() })); return { session, owner, capsule }; }
async function providerBinding() { const result = await createDocumentSynthesisProviderBindingForTest({ readSettings: async () => SETTINGS, attest: async () => ATTESTATION }).bind(); assert.equal(result.status, 'available'); if (result.status !== 'available') throw new Error('synthetic binding unavailable'); return { token: result.token, receipt: result.receipt }; }
async function providerToken() { return (await providerBinding()).token; }
async function admitted(state = fixture()) { const binding = await providerBinding(); const result = admitDocumentSynthesisFabric(Object.freeze({ ...state, providerToken: binding.token })); assert.equal(result.status, 'available'); if (result.status !== 'available' || !result.token) throw new Error('synthetic admission unavailable'); return { result, state, providerToken: binding.token, bindingReceipt: binding.receipt }; }

test('claims once in B2ab handoff resolution without prompt, source, or binding-receipt authority', async () => {
    const { result, providerToken } = await admitted(); assert.ok(resolveDocumentSynthesisProviderBinding(providerToken)); const first = beginDocumentSynthesisFabricExecution(result.token); assert.ok(first); assert.deepEqual(Reflect.ownKeys(first), []); assert.equal(beginDocumentSynthesisFabricExecution(result.token), null); const execution = resolveDocumentSynthesisFabricExecutionHandoff(first); assert.ok(execution); assert.equal(claimDocumentSynthesisProviderBindingForExecution(providerToken)?.status, 'spent'); assert.equal(resolveDocumentSynthesisFabricExecutionHandoff(first), null); assert.deepEqual(Reflect.ownKeys(execution), ['resolution', 'execution']); for (const key of ['prompt', 'lease', 'receipt', 'provenance', 'providerReceipt', 'authorityPlane', 'bindingReceipt']) assert.equal(Reflect.ownKeys(execution).includes(key), false); assert.equal(JSON.stringify(execution).includes('mediflow.document-synthesis.provider-binding.v1'), false); assert.equal(Object.isFrozen(execution.resolution), true); assert.ok(execution.execution);
});

test('requires take then source validation before finalization and keeps provider execution absent', async () => {
    const { result } = await admitted(); const handoff = beginDocumentSynthesisFabricExecution(result.token); assert.ok(handoff); const execution = resolveDocumentSynthesisFabricExecutionHandoff(handoff); assert.ok(execution); assert.equal(execution.execution.finalize(), null); assert.equal(execution.execution.takeProviderInput(), null);
    const next = await admitted(); const nextHandoff = beginDocumentSynthesisFabricExecution(next.result.token); assert.ok(nextHandoff); const ready = resolveDocumentSynthesisFabricExecutionHandoff(nextHandoff); assert.ok(ready); const input = ready.execution.takeProviderInput(); assert.ok(input); assert.equal(input.prompt.includes('Synthetic source.'), true); const validated = ready.execution.validateProviderEnvelope(envelope()); assert.equal(validated.status, 'available'); assert.equal(Object.getPrototypeOf(validated), null); const executionProjection = { ...ready }; assert.deepEqual(Reflect.ownKeys(executionProjection), ['resolution', 'execution']); assert.equal(JSON.stringify(executionProjection).includes('publication'), false); assert.equal(JSON.stringify(executionProjection).includes('provider-binding'), false); const publication = ready.execution.finalize(); assert.ok(publication); assert.equal(Object.getPrototypeOf(publication), null); assert.equal(Object.isFrozen(publication), true); assert.deepEqual(Reflect.ownKeys(publication), ['schemaVersion', 'output', 'citations', 'claims', 'receipt', 'provenance']); assert.strictEqual(publication.output, validated.output); assert.strictEqual(publication.citations, validated.citations); assert.strictEqual(publication.claims, validated.claims); assert.equal(Object.getPrototypeOf(publication.receipt), null); assert.equal(Object.isFrozen(publication.receipt), true); assert.deepEqual(Reflect.ownKeys(publication.receipt), ['schemaVersion', 'capability', 'outputSha256', 'claimCitationsDigestSha256', 'sourceSetDigestSha256', 'providerBindingReceipt', 'reviewOnly', 'applyPolicy', 'writesPerformed']); assert.strictEqual(publication.receipt.providerBindingReceipt, next.bindingReceipt); assert.equal(Object.getPrototypeOf(publication.provenance), null); assert.equal(Object.isFrozen(publication.provenance), true); assert.deepEqual(Reflect.ownKeys(publication.provenance), ['schemaVersion', 'capability', 'sourceSetAuthority', 'inputDigestScope', 'citationSupport', 'modelCausality', 'fabricProvenance']); assert.equal(ready.execution.finalize(), null);
});

test('denies validation mismatch, transition, abort, and retained handoffs after disposal', async () => {
    const denied = await admitted(); const handoff = beginDocumentSynthesisFabricExecution(denied.result.token); assert.ok(handoff); const execution = resolveDocumentSynthesisFabricExecutionHandoff(handoff); assert.ok(execution); assert.ok(execution.execution.takeProviderInput()); assert.equal(execution.execution.validateProviderEnvelope(envelope('Other source.')).status, 'denied'); assert.equal(execution.execution.finalize(), null);
    const drift = await admitted(); const driftHandoff = beginDocumentSynthesisFabricExecution(drift.result.token); assert.ok(driftHandoff); const active = resolveDocumentSynthesisFabricExecutionHandoff(driftHandoff); assert.ok(active); assert.ok(active.execution.takeProviderInput()); assert.equal(drift.state.capsule.transition(source(4, 'Beta source.')), true); assert.equal(active.execution.validateProviderEnvelope(envelope()).status, 'available'); assert.equal(active.execution.finalize(), null);
    const postPrecomputeDrift = await admitted(); const postPrecomputeHandoff = beginDocumentSynthesisFabricExecution(postPrecomputeDrift.result.token); assert.ok(postPrecomputeHandoff); const postPrecompute = resolveDocumentSynthesisFabricExecutionHandoff(postPrecomputeHandoff); assert.ok(postPrecompute); assert.ok(postPrecompute.execution.takeProviderInput()); assert.equal(postPrecompute.execution.validateProviderEnvelope(envelope()).status, 'available'); assert.equal(postPrecomputeDrift.state.capsule.transition(source(4, 'Beta source.')), true); assert.equal(postPrecompute.execution.finalize(), null);
    const disposed = await admitted(); const retained = beginDocumentSynthesisFabricExecution(disposed.result.token); assert.ok(retained); disposeDocumentSynthesisFabricAdmission(disposed.result.token); assert.equal(resolveDocumentSynthesisFabricExecutionHandoff(retained), null); const aborted = await admitted(); const abortedHandoff = beginDocumentSynthesisFabricExecution(aborted.result.token); assert.ok(abortedHandoff); const abortExecution = resolveDocumentSynthesisFabricExecutionHandoff(abortedHandoff); assert.ok(abortExecution); abortExecution.execution.abort(); assert.equal(abortExecution.execution.takeProviderInput(), null); assert.equal(abortExecution.execution.finalize(), null);
});

test('delegates every finalized capability reentry to the poisoned C-c1 lease guard', async () => {
    const nested = [
        (execution: NonNullable<ReturnType<typeof resolveDocumentSynthesisFabricExecutionHandoff>>) => execution.execution.takeProviderInput(),
        (execution: NonNullable<ReturnType<typeof resolveDocumentSynthesisFabricExecutionHandoff>>) => execution.execution.validateProviderEnvelope(envelope()),
        (execution: NonNullable<ReturnType<typeof resolveDocumentSynthesisFabricExecutionHandoff>>) => execution.execution.finalize(),
        (execution: NonNullable<ReturnType<typeof resolveDocumentSynthesisFabricExecutionHandoff>>) => execution.execution.abort(),
    ] as const;
    for (const invoke of nested) {
        let active: ReturnType<typeof resolveDocumentSynthesisFabricExecutionHandoff> = null; let armed = false; let portReads = 0; let reentries = 0;
        const state = fixture(() => { if (armed && (portReads += 1) === 2) { reentries += 1; if (active) invoke(active); } return 1_000; }); const current = await admitted(state); const handoff = beginDocumentSynthesisFabricExecution(current.result.token); assert.ok(handoff); active = resolveDocumentSynthesisFabricExecutionHandoff(handoff); assert.ok(active); assert.ok(active.execution.takeProviderInput()); assert.equal(active.execution.validateProviderEnvelope(envelope()).status, 'available'); armed = true;
        assert.equal(active.execution.finalize(), null); assert.equal(reentries, 1); const closedReads = portReads; assert.equal(active.execution.takeProviderInput(), null); assert.equal(active.execution.validateProviderEnvelope(envelope()).status, 'denied'); assert.equal(active.execution.finalize(), null); active.execution.abort(); assert.equal(portReads, closedReads);
    }
});

test('rejects foreign, cloned, proxied, accessor, thenable, and ambient-then inputs with no traps or deferred work', async () => {
    const state = fixture(); const token = await providerToken(); let reads = 0; let traps = 0; const accessor = Object.freeze(Object.defineProperty({ owner: state.owner, session: state.session, capsule: state.capsule, providerToken: token }, 'owner', { enumerable: true, get() { reads += 1; return state.owner; } })); const proxy = new Proxy(Object.freeze({ owner: state.owner, session: state.session, capsule: state.capsule, providerToken: token }), { get() { traps += 1; throw new Error('trap'); } }); for (const value of [accessor, proxy, Object.freeze({ owner: state.owner, session: state.session, capsule: state.capsule, providerToken: token, then() {} })]) assert.equal(admitDocumentSynthesisFabric(value).status, 'denied');
    const { result } = await admitted(); const descriptor = Object.getOwnPropertyDescriptor(Object.prototype, 'then'); Object.defineProperty(Object.prototype, 'then', { configurable: true, get() { reads += 1; return undefined; } }); assert.equal(beginDocumentSynthesisFabricExecution(new Proxy(result.token!, { get() { traps += 1; throw new Error('trap'); } })), null); if (descriptor) Object.defineProperty(Object.prototype, 'then', descriptor); else delete (Object.prototype as { then?: unknown }).then; assert.equal(reads, 0); assert.equal(traps, 0); await new Promise<void>((resolve) => setImmediate(resolve));
    const safe = await admitted(); const safeHandoff = beginDocumentSynthesisFabricExecution(safe.result.token); assert.ok(safeHandoff); const safeExecution = resolveDocumentSynthesisFabricExecutionHandoff(safeHandoff); assert.ok(safeExecution); const unhandled: unknown[] = []; const listener = (reason: unknown) => { unhandled[unhandled.length] = reason; }; process.on('unhandledRejection', listener); Object.defineProperty(Object.prototype, 'then', { configurable: true, get() { throw new Error('ambient'); } }); try { assert.ok(safeExecution.execution.takeProviderInput()); assert.equal(safeExecution.execution.validateProviderEnvelope(envelope()).status, 'available'); assert.ok(safeExecution.execution.finalize()); } finally { if (descriptor) Object.defineProperty(Object.prototype, 'then', descriptor); else delete (Object.prototype as { then?: unknown }).then; } await new Promise<void>((resolve) => setImmediate(resolve)); process.off('unhandledRejection', listener); assert.deepEqual(unhandled, []);
    const original = types.isProxy; types.isProxy = () => false; try { assert.equal(resolveDocumentSynthesisFabricExecutionHandoff(Object.freeze({})), null); } finally { types.isProxy = original; }
});

test('precomputes ADR 0102 evidence privately and returns it only in the strict commit-last success arm', async () => {
    const source = await readFile('lib/ai-providers/fabric/document-synthesis-fabric-admission.ts', 'utf8');
    assert.match(source, /digestDocumentSynthesisClaimCitations\(validation\)/u); assert.match(source, /entry\.publication = publication/u); assert.match(source, /output: validation\.output, citations: validation\.citations, claims: validation\.claims/u); assert.match(source, /sourceSetDigestSha256: validation\.sourceSetDigestSha256, providerBindingReceipt: bindingReceipt/u); assert.match(source, /prepared\.provenance\.receipt !== prepared\.receipt/u); assert.match(source, /fabricProvenance: prepared\.provenance/u); assert.match(source, /entry\.state = 'finalized'; try \{ if \(!lease\.consume\(executionToken\)\) \{ deny\(\); return null; \} return publication; \} catch/u); assert.match(source, /const denyFinalized = \(\) => \{ const executionToken = entry\.executionToken; if \(executionToken\) entry\.lease\.takeProviderInput\(executionToken\); \}/u); assert.doesNotMatch(source, /\b(?:committing|committingLease|reentry|finally|structuredClone)\b|JSON\.(?:parse|stringify)/u); assert.doesNotMatch(source, /providerBindingReceipt:\s*\{[^}]/u);
});
