/* @Codex */
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { afterEach, test } from 'node:test';

import { OllamaProviderAdapter } from '../ollama.ts';
import { admitDocumentSynthesisFabric, beginDocumentSynthesisFabricExecution } from './document-synthesis-fabric-admission.ts';
import { cancelDocumentSynthesisFabricExecutionPrepare, disposeDocumentSynthesisFabricPreparedExecution, prepareDocumentSynthesisFabricExecution, setDocumentSynthesisFabricExecutionPrepareTimeoutForTest } from './document-synthesis-fabric-execution-prepare.ts';
import { createDocumentSynthesisProviderBindingForTest } from './document-synthesis-provider-binding.ts';
import { executeDocumentSynthesisProvider } from './document-synthesis-provider-execution.ts';
import { captureDocumentSynthesisSourceSet } from './document-synthesis-source-set-contract.ts';
import { createDocumentSynthesisSourceSetCurrentnessOwner } from './document-synthesis-source-set-currentness-owner.ts';
import { createServerSessionProjectionOwnerRegistry } from '../../security/server-session-projection-owner.ts';
import { clearAllSessions, createSession } from '../../security/server-session.ts';

const SETTINGS = Object.freeze({ aiProvider: 'ollama', aiModel_reasoning: 'reasoning-local', aiUrl: 'http://localhost:11434' }); const ATTESTATION = Object.freeze({ authorityPlane: 'clinical_application', provider: 'ollama', executionMode: 'local', endpointClass: 'loopback', requestedModel: 'reasoning-local', canonicalModel: 'reasoning-local:latest', digest: 'sha256:synthetic', serverVersion: '0.32.5', checkedAt: '2026-08-25T12:00:00.000Z' }); const USER = Object.freeze({ id: ['synthetic', 'ds', 'prepare', 'user'].join('.'), username: ['synthetic', 'ds', 'prepare', 'clinician'].join('.'), role: 'clinician' as const }); const PAIR = Object.freeze({ patientId: 'patient.synthetic.ds.prepare', ambulatoryId: 'ambulatory.synthetic.ds.prepare' });
afterEach(() => clearAllSessions());
function body(text = 'Synthetic source.') { const digest = createHash('sha256').update(new TextEncoder().encode(text)).digest('hex'); return JSON.stringify({ output: { schemaVersion: 'mediflow.ai.extract.v1', task: 'document_synthesis', summary: 'Synthetic summary', data: { qualityLevel: 'green', medications: [], diagnoses: [], problemStatements: [], therapyCandidates: [], servicePrescriptions: [] } }, citations: [{ label: 'S1', quote: text, startByte: 0, endByte: new TextEncoder().encode(text).length, quoteSha256: digest }], claims: [{ claimPath: 'summary', labels: ['S1'] }, { claimPath: 'data.qualityLevel', labels: ['S1'] }] }); }
async function handoff(chat: OllamaProviderAdapter['chat']) { const original = OllamaProviderAdapter.prototype.chat; OllamaProviderAdapter.prototype.chat = chat; let entropy = 0; const registry = createServerSessionProjectionOwnerRegistry({ clock: () => 1_000, entropy: () => Uint8Array.from({ length: 16 }, (_, index) => (entropy += 1) + index), resolve: (_session, pair) => Object.freeze({ ...pair }) }); const session = createSession(USER, 'web'); const owner = registry.acquire(session); owner.issueSelection({ expectedEpoch: 0, ...PAIR }); const captured = captureDocumentSynthesisSourceSet({ sourceSetEpoch: BigInt(3), revocationGeneration: BigInt(5), sources: [{ documentSourceRef: 'document.synthetic.ds.prepare', documentRevision: BigInt(7), documentFreshnessEpoch: BigInt(11), sourceText: 'Synthetic source.' }] }); assert.equal(captured.status, 'available'); if (captured.status !== 'available') throw new Error('source'); const capsule = createDocumentSynthesisSourceSetCurrentnessOwner(Object.freeze({ owner, session, sourceSet: captured.sourceSet })); const binding = await createDocumentSynthesisProviderBindingForTest({ readSettings: async () => SETTINGS, attest: async () => ATTESTATION }).bind(); assert.equal(binding.status, 'available'); if (binding.status !== 'available') throw new Error('binding'); const admitted = admitDocumentSynthesisFabric(Object.freeze({ owner, session, capsule, providerToken: binding.token })); assert.equal(admitted.status, 'available'); const value = admitted.token && beginDocumentSynthesisFabricExecution(admitted.token); assert.ok(value); return { value, providerToken: binding.token, restore() { OllamaProviderAdapter.prototype.chat = original; } }; }
function exact(result: Awaited<ReturnType<typeof prepareDocumentSynthesisFabricExecution>>, code: string) { assert.deepEqual({ ...result }, { status: 'denied', code, preparedToken: null, reviewOnly: true, writesPerformed: 0, applyPolicy: 'none', fallback: 'denied_by_contract' }); }

test('prepares one fixed lease-bound prompt with no output leakage or finalization', { concurrency: false }, async () => { const calls: unknown[][] = []; const fixture = await handoff(async (...args) => { calls.push(args); return { content: body(), stats: { latency: 0, tokensIn: 0, tokensOut: 0 } }; }); try { const result = await prepareDocumentSynthesisFabricExecution(fixture.value); assert.equal(result.status, 'available'); if (result.status !== 'available') return; const message = calls[0]?.[0] as Array<{ role: string; content: string }>; assert.equal(message.length, 1); assert.equal(message[0]?.role, 'user'); assert.equal(message[0]?.content.includes('Synthetic source.'), true); assert.equal(calls.length, 1); assert.equal(calls[0]?.[1] instanceof AbortSignal, true); assert.equal(calls[0]?.[2], 1400); assert.deepEqual(calls[0]?.[3], { responseFormat: 'json' }); assert.equal(Object.getPrototypeOf(result), null); assert.equal(Object.isFrozen(result), true); assert.deepEqual(Reflect.ownKeys(result), ['status', 'code', 'preparedToken', 'reviewOnly', 'writesPerformed', 'applyPolicy', 'fallback']); assert.deepEqual(Reflect.ownKeys(result.preparedToken), []); disposeDocumentSynthesisFabricPreparedExecution(result.preparedToken); } finally { fixture.restore(); } });

test('denies replay and hostile inputs without a second provider call', { concurrency: false }, async () => { let calls = 0; const fixture = await handoff(async () => { calls += 1; return { content: body(), stats: { latency: 0, tokensIn: 0, tokensOut: 0 } }; }); try { const first = prepareDocumentSynthesisFabricExecution(fixture.value); exact(await prepareDocumentSynthesisFabricExecution(fixture.value), 'canceled'); exact(await first, 'canceled'); assert.equal(calls, 1); for (const value of [{}, { ...fixture.value }, structuredClone(fixture.value), Object.freeze(Object.defineProperty({}, 'then', { value() {} }))]) exact(await prepareDocumentSynthesisFabricExecution(value), 'handoff_unavailable'); exact(await prepareDocumentSynthesisFabricExecution(new Proxy(fixture.value, {})), 'input_invalid'); } finally { fixture.restore(); } });

test('lets prepare retain the single claim when the legacy executor races it', { concurrency: false }, async () => { let calls = 0; const fixture = await handoff(async () => { calls += 1; return { content: body(), stats: { latency: 0, tokensIn: 0, tokensOut: 0 } }; }); try { const preparing = prepareDocumentSynthesisFabricExecution(fixture.value); const legacy = await executeDocumentSynthesisProvider({ projection: { schemaVersion: 'mediflow.document-synthesis.host-projection.v1', sourceKind: 'ocr_text', sourceText: 'Synthetic source.', classification: 'review_required', rationale: 'ocr_text_normalized' }, providerToken: fixture.providerToken }); const result = await preparing; assert.equal(result.status, 'available'); assert.equal(legacy.status, 'denied'); if (legacy.status === 'denied') { assert.equal(legacy.receipt, null); assert.equal(legacy.provenance, null); } assert.equal(calls, 1); if (result.status === 'available') disposeDocumentSynthesisFabricPreparedExecution(result.preparedToken); } finally { fixture.restore(); } });

test('burns the claim after timeout, malformed envelope, or source validation denial', { concurrency: false }, async () => { for (const [content, code] of [[null, 'response_invalid'], [body('Different synthetic source.'), 'validation_denied']] as const) { let calls = 0; const fixture = await handoff(async () => { calls += 1; return { content: content as string, stats: { latency: 0, tokensIn: 0, tokensOut: 0 } }; }); try { const result = await prepareDocumentSynthesisFabricExecution(fixture.value); exact(result, code); const legacy = await executeDocumentSynthesisProvider({ projection: { schemaVersion: 'mediflow.document-synthesis.host-projection.v1', sourceKind: 'ocr_text', sourceText: 'Synthetic source.', classification: 'review_required', rationale: 'ocr_text_normalized' }, providerToken: fixture.providerToken }); assert.equal(legacy.status, 'denied'); if (legacy.status === 'denied') { assert.equal(legacy.receipt, null); assert.equal(legacy.provenance, null); } assert.equal(calls, 1); } finally { fixture.restore(); } } });

test('aborts timeout or cancellation, burns the claim, absorbs late rejection, and skips parse validation after return', { concurrency: false }, async () => { let rejectLate!: (reason: unknown) => void; const fixture = await handoff(async () => new Promise((_, reject) => { rejectLate = reject; })); const restore = setDocumentSynthesisFabricExecutionPrepareTimeoutForTest(0); const unhandled: unknown[] = []; const listener = (reason: unknown) => { unhandled.push(reason); }; process.on('unhandledRejection', listener); try { exact(await prepareDocumentSynthesisFabricExecution(fixture.value), 'provider_timeout'); const legacy = await executeDocumentSynthesisProvider({ projection: { schemaVersion: 'mediflow.document-synthesis.host-projection.v1', sourceKind: 'ocr_text', sourceText: 'Synthetic source.', classification: 'review_required', rationale: 'ocr_text_normalized' }, providerToken: fixture.providerToken }); assert.equal(legacy.status, 'denied'); if (legacy.status === 'denied') { assert.equal(legacy.receipt, null); assert.equal(legacy.provenance, null); } rejectLate(new Error('late')); await new Promise<void>((resolve) => setImmediate(resolve)); assert.deepEqual(unhandled, []); } finally { process.off('unhandledRejection', listener); restore?.(); fixture.restore(); } });

test('cancellation accepts only authentic active handoffs and burns the claim', { concurrency: false }, async () => { let release!: () => void; const fixture = await handoff(async () => new Promise((resolve) => { release = () => resolve({ content: body(), stats: { latency: 0, tokensIn: 0, tokensOut: 0 } }); })); const unhandled: unknown[] = []; const listener = (reason: unknown) => { unhandled.push(reason); }; process.on('unhandledRejection', listener); try { const pending = prepareDocumentSynthesisFabricExecution(fixture.value); await new Promise<void>((resolve) => setImmediate(resolve)); cancelDocumentSynthesisFabricExecutionPrepare({}); cancelDocumentSynthesisFabricExecutionPrepare(new Proxy(fixture.value, {})); cancelDocumentSynthesisFabricExecutionPrepare(fixture.value); exact(await pending, 'canceled'); const legacy = await executeDocumentSynthesisProvider({ projection: { schemaVersion: 'mediflow.document-synthesis.host-projection.v1', sourceKind: 'ocr_text', sourceText: 'Synthetic source.', classification: 'review_required', rationale: 'ocr_text_normalized' }, providerToken: fixture.providerToken }); assert.equal(legacy.status, 'denied'); if (legacy.status === 'denied') { assert.equal(legacy.receipt, null); assert.equal(legacy.provenance, null); } release(); await new Promise<void>((resolve) => setImmediate(resolve)); assert.deepEqual(unhandled, []); } finally { process.off('unhandledRejection', listener); fixture.restore(); } });
