/* @Codex */
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { afterEach, test } from 'node:test';
import { types } from 'node:util';

import { admitDocumentSynthesisFabric, beginDocumentSynthesisFabricExecution, disposeDocumentSynthesisFabricAdmission, resolveDocumentSynthesisFabricExecutionHandoff } from './document-synthesis-fabric-admission.ts';
import { createDocumentSynthesisProviderBindingForTest } from './document-synthesis-provider-binding.ts';
import { parseDocumentSynthesisProviderEnvelope } from './document-synthesis-provider-envelope.ts';
import { captureDocumentSynthesisSourceSet } from './document-synthesis-source-set-contract.ts';
import { createDocumentSynthesisSourceSetCurrentnessOwner } from './document-synthesis-source-set-currentness-owner.ts';
import { createServerSessionProjectionOwnerRegistry } from '../../security/server-session-projection-owner.ts';
import { clearAllSessions, createSession } from '../../security/server-session.ts';

const USER = { id: ['synthetic', 'fabric', 'admission', 'user'].join('.'), username: ['synthetic', 'fabric', 'admission', 'clinician'].join('.'), role: 'clinician' }; const PAIR = { patientId: 'patient.synthetic.fabric.admission', ambulatoryId: 'ambulatory.synthetic.fabric.admission' }; const SETTINGS = Object.freeze({ aiProvider: 'ollama', aiModel_reasoning: 'reasoning-local', aiUrl: 'http://localhost:11434' }); const ATTESTATION = Object.freeze({ authorityPlane: 'clinical_application', provider: 'ollama', executionMode: 'local', endpointClass: 'loopback', requestedModel: 'reasoning-local', canonicalModel: 'reasoning-local:latest', digest: 'sha256:synthetic', serverVersion: '0.32.5', checkedAt: '2026-08-25T12:00:00.000Z' });
afterEach(() => clearAllSessions());
function source(epoch = 3, text = 'Synthetic source.') { const result = captureDocumentSynthesisSourceSet({ sourceSetEpoch: BigInt(epoch), revocationGeneration: BigInt(5), sources: [{ documentSourceRef: 'document.synthetic.fabric.admission', documentRevision: BigInt(7), documentFreshnessEpoch: BigInt(11), sourceText: text }] }); assert.equal(result.status, 'available'); if (result.status !== 'available') throw new Error('synthetic source unavailable'); return result.sourceSet; }
function envelope(text = 'Synthetic source.') { const quoteSha256 = createHash('sha256').update(new TextEncoder().encode(text)).digest('hex'); const result = parseDocumentSynthesisProviderEnvelope({ content: JSON.stringify({ output: { schemaVersion: 'mediflow.ai.extract.v1', task: 'document_synthesis', summary: 'Synthetic summary', data: { qualityLevel: 'green', medications: [], diagnoses: [], problemStatements: [], therapyCandidates: [], servicePrescriptions: [] } }, citations: [{ label: 'S1', quote: text, startByte: 0, endByte: new TextEncoder().encode(text).length, quoteSha256 }], claims: [{ claimPath: 'summary', labels: ['S1'] }, { claimPath: 'data.qualityLevel', labels: ['S1'] }] }) }); assert.equal(result.status, 'available'); if (result.status !== 'available') throw new Error('synthetic envelope unavailable'); return result.token; }
function fixture() { let entropy = 0; const registry = createServerSessionProjectionOwnerRegistry({ clock: () => 1_000, entropy: () => Uint8Array.from({ length: 16 }, (_, index) => (entropy += 1) + index), resolve: (_session, pair) => Object.freeze({ ...pair }) }); const session = createSession(USER, 'web'); const owner = registry.acquire(session); owner.issueSelection({ expectedEpoch: 0, ...PAIR }); const capsule = createDocumentSynthesisSourceSetCurrentnessOwner(Object.freeze({ owner, session, sourceSet: source() })); return { session, owner, capsule }; }
async function providerToken() { const result = await createDocumentSynthesisProviderBindingForTest({ readSettings: async () => SETTINGS, attest: async () => ATTESTATION }).bind(); assert.equal(result.status, 'available'); if (result.status !== 'available') throw new Error('synthetic binding unavailable'); return result.token; }
async function admitted(state = fixture()) { const result = admitDocumentSynthesisFabric(Object.freeze({ ...state, providerToken: await providerToken() })); assert.equal(result.status, 'available'); if (result.status !== 'available' || !result.token) throw new Error('synthetic admission unavailable'); return { result, state }; }

test('begins exactly one opaque handoff and resolves it once without prompt or source authority', async () => {
    const { result } = await admitted(); const first = beginDocumentSynthesisFabricExecution(result.token); assert.ok(first); assert.deepEqual(Reflect.ownKeys(first), []); assert.equal(beginDocumentSynthesisFabricExecution(result.token), null); const execution = resolveDocumentSynthesisFabricExecutionHandoff(first); assert.ok(execution); assert.equal(resolveDocumentSynthesisFabricExecutionHandoff(first), null); assert.deepEqual(Reflect.ownKeys(execution), ['providerToken', 'execution']); for (const key of ['prompt', 'lease', 'receipt', 'provenance', 'providerReceipt', 'authorityPlane']) assert.equal(Reflect.ownKeys(execution).includes(key), false); assert.ok(execution.execution);
});

test('requires take then source validation before finalization and keeps provider execution absent', async () => {
    const { result } = await admitted(); const handoff = beginDocumentSynthesisFabricExecution(result.token); assert.ok(handoff); const execution = resolveDocumentSynthesisFabricExecutionHandoff(handoff); assert.ok(execution); assert.equal(execution.execution.finalize(), null); assert.equal(execution.execution.takeProviderInput(), null);
    const next = await admitted(); const nextHandoff = beginDocumentSynthesisFabricExecution(next.result.token); assert.ok(nextHandoff); const ready = resolveDocumentSynthesisFabricExecutionHandoff(nextHandoff); assert.ok(ready); const input = ready.execution.takeProviderInput(); assert.ok(input); assert.equal(input.prompt.includes('Synthetic source.'), true); assert.equal(ready.execution.validateProviderEnvelope(envelope()).status, 'available'); const committed = ready.execution.finalize(); assert.ok(committed); assert.equal(Object.getPrototypeOf(committed), null); assert.equal(Object.isFrozen(committed), true); assert.deepEqual(Reflect.ownKeys(committed), ['receipt', 'provenance']); assert.equal(committed.receipt.capability, 'document_synthesis'); assert.equal(ready.execution.finalize(), null);
});

test('denies validation mismatch, transition, abort, and retained handoffs after disposal', async () => {
    const denied = await admitted(); const handoff = beginDocumentSynthesisFabricExecution(denied.result.token); assert.ok(handoff); const execution = resolveDocumentSynthesisFabricExecutionHandoff(handoff); assert.ok(execution); assert.ok(execution.execution.takeProviderInput()); assert.equal(execution.execution.validateProviderEnvelope(envelope('Other source.')).status, 'denied'); assert.equal(execution.execution.finalize(), null);
    const drift = await admitted(); const driftHandoff = beginDocumentSynthesisFabricExecution(drift.result.token); assert.ok(driftHandoff); const active = resolveDocumentSynthesisFabricExecutionHandoff(driftHandoff); assert.ok(active); assert.ok(active.execution.takeProviderInput()); assert.equal(drift.state.capsule.transition(source(4, 'Beta source.')), true); assert.equal(active.execution.validateProviderEnvelope(envelope()).status, 'available'); assert.equal(active.execution.finalize(), null);
    const disposed = await admitted(); const retained = beginDocumentSynthesisFabricExecution(disposed.result.token); assert.ok(retained); disposeDocumentSynthesisFabricAdmission(disposed.result.token); assert.equal(resolveDocumentSynthesisFabricExecutionHandoff(retained), null); const aborted = await admitted(); const abortedHandoff = beginDocumentSynthesisFabricExecution(aborted.result.token); assert.ok(abortedHandoff); const abortExecution = resolveDocumentSynthesisFabricExecutionHandoff(abortedHandoff); assert.ok(abortExecution); abortExecution.execution.abort(); assert.equal(abortExecution.execution.takeProviderInput(), null); assert.equal(abortExecution.execution.finalize(), null);
});

test('rejects foreign, cloned, proxied, accessor, thenable, and ambient-then inputs with no traps or deferred work', async () => {
    const state = fixture(); const token = await providerToken(); let reads = 0; let traps = 0; const accessor = Object.freeze(Object.defineProperty({ owner: state.owner, session: state.session, capsule: state.capsule, providerToken: token }, 'owner', { enumerable: true, get() { reads += 1; return state.owner; } })); const proxy = new Proxy(Object.freeze({ owner: state.owner, session: state.session, capsule: state.capsule, providerToken: token }), { get() { traps += 1; throw new Error('trap'); } }); for (const value of [accessor, proxy, Object.freeze({ owner: state.owner, session: state.session, capsule: state.capsule, providerToken: token, then() {} })]) assert.equal(admitDocumentSynthesisFabric(value).status, 'denied');
    const { result } = await admitted(); const descriptor = Object.getOwnPropertyDescriptor(Object.prototype, 'then'); Object.defineProperty(Object.prototype, 'then', { configurable: true, get() { reads += 1; return undefined; } }); assert.equal(beginDocumentSynthesisFabricExecution(new Proxy(result.token!, { get() { traps += 1; throw new Error('trap'); } })), null); if (descriptor) Object.defineProperty(Object.prototype, 'then', descriptor); else delete (Object.prototype as { then?: unknown }).then; assert.equal(reads, 0); assert.equal(traps, 0); await new Promise<void>((resolve) => setImmediate(resolve));
    const safe = await admitted(); const safeHandoff = beginDocumentSynthesisFabricExecution(safe.result.token); assert.ok(safeHandoff); const safeExecution = resolveDocumentSynthesisFabricExecutionHandoff(safeHandoff); assert.ok(safeExecution); const unhandled: unknown[] = []; const listener = (reason: unknown) => { unhandled[unhandled.length] = reason; }; process.on('unhandledRejection', listener); Object.defineProperty(Object.prototype, 'then', { configurable: true, get() { throw new Error('ambient'); } }); try { assert.ok(safeExecution.execution.takeProviderInput()); assert.equal(safeExecution.execution.validateProviderEnvelope(envelope()).status, 'available'); assert.ok(safeExecution.execution.finalize()); } finally { if (descriptor) Object.defineProperty(Object.prototype, 'then', descriptor); else delete (Object.prototype as { then?: unknown }).then; } await new Promise<void>((resolve) => setImmediate(resolve)); process.off('unhandledRejection', listener); assert.deepEqual(unhandled, []);
    const original = types.isProxy; types.isProxy = () => false; try { assert.equal(resolveDocumentSynthesisFabricExecutionHandoff(Object.freeze({})), null); } finally { types.isProxy = original; }
});
