/* @Codex */
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { createRequire, syncBuiltinESMExports } from 'node:module';
import { afterEach, test } from 'node:test';
import { types } from 'node:util';

import { digestDocumentSynthesisClaimCitations } from './document-synthesis-claim-citations-digest';
import { parseDocumentSynthesisProviderEnvelope } from './document-synthesis-provider-envelope';
import { captureDocumentSynthesisSourceSet } from './document-synthesis-source-set-contract';
import { createDocumentSynthesisSourceSetCurrentnessOwner } from './document-synthesis-source-set-currentness-owner';
import { createDocumentSynthesisSourceSetLease } from './document-synthesis-source-set-lease';
import { createServerSessionProjectionOwnerRegistry } from '../../security/server-session-projection-owner';
import { clearAllSessions, createSession } from '../../security/server-session';

const encoder = new TextEncoder();
const nodeRequire = createRequire(import.meta.url); const crypto = nodeRequire('node:crypto') as { createHash: typeof createHash };
const USER = { id: ['synthetic', 'codec', 'user'].join('.'), username: ['synthetic', 'codec', 'clinician'].join('.'), role: 'clinician' }; const PAIR = { patientId: 'patient.synthetic.codec', ambulatoryId: 'ambulatory.synthetic.codec' };
afterEach(() => clearAllSessions());
function seal<T extends object>(value: T): Readonly<T> { return Object.freeze(Object.assign(Object.create(null), value)); }
function list<T>(values: readonly T[]): readonly T[] { const copy = [...values]; Object.defineProperty(copy, 'toJSON', { value: null, enumerable: false, configurable: false, writable: false }); return Object.freeze(copy); }
const sha = (value: string) => createHash('sha256').update(encoder.encode(value)).digest('hex');
const bytes32 = (byte = 0) => Object.freeze(Array.from({ length: 32 }, () => byte));
function value() { const citations = list([seal({ label: 'S1', quote: 'Caf\u00e9', startByte: 0, endByte: 5, quoteSha256: sha('Caf\u00e9') }), seal({ label: 'S2', quote: 'Beta', startByte: 5, endByte: 9, quoteSha256: sha('Beta') })]); return seal({ status: 'available', code: null, schemaVersion: 'mediflow.document-synthesis.claim-citations.v1', output: seal({}), outputSha256: sha('output'), citations, claims: list([seal({ claimPath: 'summary', labels: list(['S1', 'S2']) }), seal({ claimPath: 'data.qualityLevel', labels: list(['S2']) })]), reviewOnly: true, writesPerformed: 0, applyPolicy: 'none', sourceSetDigestSha256: bytes32() }); }
function denied(input: unknown): void { assert.equal(digestDocumentSynthesisClaimCitations(input), null); }
function authenticU0() { const source = captureDocumentSynthesisSourceSet({ sourceSetEpoch: BigInt(3), revocationGeneration: BigInt(5), sources: [{ documentSourceRef: 'document.synthetic.codec', documentRevision: BigInt(7), documentFreshnessEpoch: BigInt(11), sourceText: 'Synthetic source.' }] }); assert.equal(source.status, 'available'); const registry = createServerSessionProjectionOwnerRegistry({ clock: () => 1_000, entropy: () => Uint8Array.from({ length: 16 }, (_, index) => index + 1), resolve: (_session, pair) => Object.freeze({ ...pair }) }); const session = createSession(USER, 'web'); const owner = registry.acquire(session); owner.issueSelection({ expectedEpoch: 0, ...PAIR }); const capsule = createDocumentSynthesisSourceSetCurrentnessOwner(Object.freeze({ owner, session, sourceSet: source.sourceSet! })); const lease = createDocumentSynthesisSourceSetLease(Object.freeze({ owner, session, capsule })); const issue = lease.issue(); assert.ok(issue); const execution = lease.beginExecution(issue); assert.ok(execution); assert.ok(lease.takeProviderInput(execution)); const quote = 'Synthetic source.'; const parsed = parseDocumentSynthesisProviderEnvelope({ content: JSON.stringify({ output: { schemaVersion: 'mediflow.ai.extract.v1', task: 'document_synthesis', summary: 'Synthetic summary', data: { qualityLevel: 'green', medications: [], diagnoses: [], problemStatements: [], therapyCandidates: [], servicePrescriptions: [] } }, citations: [{ label: 'S1', quote, startByte: 0, endByte: encoder.encode(quote).length, quoteSha256: sha(quote) }], claims: [{ claimPath: 'summary', labels: ['S1'] }, { claimPath: 'data.qualityLevel', labels: ['S1'] }] }) }); assert.equal(parsed.status, 'available'); const result = lease.validateProviderEnvelope(Object.freeze({ executionToken: execution, envelopeToken: parsed.token! })); assert.equal(result.status, 'available'); return result; }

test('encodes the frozen ordered U0-retained pair as raw32 SHA-256', () => {
    const input = value(); const actual = digestDocumentSynthesisClaimCitations(input); assert.ok(actual); assert.equal(Object.isFrozen(actual), true); assert.equal(Object.getOwnPropertyDescriptor(actual, 'toJSON')?.value, null);
    const p: number[] = []; const put = (v: number[]) => p.push(...v); const u32 = (v: number) => put([(v >>> 24) & 255, (v >>> 16) & 255, (v >>> 8) & 255, v & 255]); const u64 = (v: number) => { const n = BigInt(v); for (let i = 7; i >= 0; i -= 1) p.push(Number((n >> BigInt(i * 8)) & BigInt(255))); }; const hex = (s: string) => Array.from({ length: 32 }, (_, i) => Number.parseInt(s.slice(i * 2, i * 2 + 2), 16)); const text = (s: string) => { const b = [...encoder.encode(s)]; u32(b.length); put(b); };
    text('mediflow.document-synthesis.claim-citations-digest.v1'); put([0, 1, 0, 2]); text('S1'); text('Caf\u00e9'); u64(0); u64(5); put(hex(sha('Caf\u00e9'))); text('S2'); text('Beta'); u64(5); u64(9); put(hex(sha('Beta'))); put([0, 2]); text('summary'); put([0, 2]); text('S1'); text('S2'); text('data.qualityLevel'); put([0, 1]); text('S2');
    assert.deepEqual(actual, [...createHash('sha256').update(Uint8Array.from(p)).digest()]);
    assert.equal(Reflect.ownKeys(input.sourceSetDigestSha256).includes('toJSON'), false);
});

test('accepts only the authentic owner U0 validation result through execution input and provider envelope resolution', () => { const result = authenticU0(); assert.equal(Object.getPrototypeOf(result), null); assert.equal(Object.isFrozen(result.sourceSetDigestSha256), true); assert.equal(Reflect.ownKeys(result.sourceSetDigestSha256).includes('toJSON'), false); assert.ok(digestDocumentSynthesisClaimCitations(result)); });

test('denies drift before hashing: authority fields, order, duplicates, sparse arrays, descriptors, Unicode, and numeric coercion', () => {
    const input = value(); denied(Object.freeze({ citations: input.citations, claims: input.claims })); denied(seal({ ...input, citations: list([seal({ ...input.citations[0]!, quoteSha256: sha('forged quote') }), input.citations[1]!]) })); denied(seal({ ...input, citations: list([seal({ ...input.citations[0]!, endByte: 4 }), input.citations[1]!]) })); denied(seal({ ...input, sourceSetDigestSha256: list(bytes32()) })); denied(seal({ ...input, sourceSetDigestSha256: Object.freeze([0]) })); const accessor = Object.create(null); Object.defineProperty(accessor, 'status', { enumerable: true, get() { throw new Error('read'); } }); denied(Object.freeze(accessor)); denied(new Proxy(value(), {}));
});

test('remains synchronous and deterministic after ambient intrinsic poisoning', () => {
    const input = value(); const baseline = digestDocumentSynthesisClaimCitations(input); const define = Object.defineProperty; const get = Object.getOwnPropertyDescriptor; const probe = createHash('sha256'); const proto = Object.getPrototypeOf(probe); const targets = [[Object, 'create'], [Object, 'freeze'], [Object, 'getOwnPropertyDescriptor'], [Object, 'getPrototypeOf'], [Object, 'hasOwn'], [Object, 'isFrozen'], [Reflect, 'apply'], [Reflect, 'ownKeys'], [Array, 'isArray'], [TextEncoder.prototype, 'encode'], [types, 'isProxy'], [proto, 'update'], [proto, 'digest']] as const; const saved = targets.map(([o, k]) => [o, k, get(o, k)!] as const); const poison = () => { throw new Error('poison'); }; let actual: ReturnType<typeof digestDocumentSynthesisClaimCitations>;
    try { for (const [o, k, d] of saved) define(o, k, { ...d, value: poison }); actual = digestDocumentSynthesisClaimCitations(input); } finally { for (const [o, k, d] of saved) define(o, k, d); }
    assert.deepEqual(actual!, baseline); assert.equal(actual! instanceof Promise, false);
});

test('uses indexed payload copying after post-import Array iterator poison for authentic U0', async () => { const input = authenticU0(); const baseline = digestDocumentSynthesisClaimCitations(input); const define = Object.defineProperty; const descriptor = Object.getOwnPropertyDescriptor(Array.prototype, Symbol.iterator)!; let calls = 0; let actual: ReturnType<typeof digestDocumentSynthesisClaimCitations>; let unhandled = 0; const listener = () => { unhandled += 1; }; process.on('unhandledRejection', listener); try { define(Array.prototype, Symbol.iterator, { ...descriptor, value() { calls += 1; throw new Error('iterator poison'); } }); actual = digestDocumentSynthesisClaimCitations(input); } finally { define(Array.prototype, Symbol.iterator, descriptor); await new Promise<void>((resolve) => setImmediate(resolve)); process.off('unhandledRejection', listener); } assert.deepEqual(actual!, baseline); assert.equal(calls, 0); assert.equal(unhandled, 0); assert.equal(actual! instanceof Promise, false); });

test('uses captured SHA-256 factory after post-import node crypto replacement for authentic U0', async () => { const input = authenticU0(); const baseline = digestDocumentSynthesisClaimCitations(input); const original = crypto.createHash; let calls = 0; let actual: ReturnType<typeof digestDocumentSynthesisClaimCitations>; let unhandled = 0; const listener = () => { unhandled += 1; }; process.on('unhandledRejection', listener); try { crypto.createHash = (() => { calls += 1; throw new Error('factory poison'); }) as typeof createHash; syncBuiltinESMExports(); actual = digestDocumentSynthesisClaimCitations(input); } finally { crypto.createHash = original; syncBuiltinESMExports(); await new Promise<void>((resolve) => setImmediate(resolve)); process.off('unhandledRejection', listener); } assert.deepEqual(actual!, baseline); assert.equal(calls, 0); assert.equal(unhandled, 0); assert.equal(actual! instanceof Promise, false); });
