/* @Codex */
import { createHash } from 'node:crypto';
import { types } from 'node:util';

const OBJECT = Object.prototype; const ARRAY = Array.prototype; const DOMAIN = 'mediflow.document-synthesis.source-set-digest.v1';
const ZERO = BigInt(0); const BYTE = BigInt(255); const SHIFT = BigInt(8); const MAX_U64 = BigInt('18446744073709551615');
const MAX_SOURCE_BYTES = 36_000; const MAX_SET_BYTES = 1_152_000; const encoder = new TextEncoder();
const ObjectCreate = Object.create; const ObjectDefineProperty = Object.defineProperty; const ObjectFreeze = Object.freeze; const ObjectGetOwnPropertyDescriptor = Object.getOwnPropertyDescriptor; const ObjectGetPrototypeOf = Object.getPrototypeOf; const ObjectHasOwn = Object.hasOwn; const ReflectOwnKeys = Reflect.ownKeys; const ReflectApply = Reflect.apply; const ArrayIsArray = Array.isArray; const IsProxy = types.isProxy; const NumberIsSafeInteger = Number.isSafeInteger; const NumberConstructor = Number; const Uint8ArrayConstructor = Uint8Array; const TextEncoderEncode = TextEncoder.prototype.encode; const StringCharCodeAt = String.prototype.charCodeAt;

type Bytes = readonly number[];
type Item = Readonly<{ label: string; documentSourceRef: string; documentRevision: bigint; documentFreshnessEpoch: bigint; sourceByteLength: number; projectionDigestSha256: Bytes }>;
type Parsed = Readonly<Item & { referenceBytes: Uint8Array }>;
export type DocumentSynthesisSourceSetDigestResult = Readonly<{ status: 'available'; code: null; digestPayloadBytes: Bytes; sourceSetDigestSha256: Bytes }> | Readonly<{ status: 'denied'; code: 'input_invalid'; digestPayloadBytes: null; sourceSetDigestSha256: null }>;

function sealed<T extends object>(value: T): Readonly<T> { const output = ObjectCreate(null) as T; const keys = ReflectOwnKeys(value); for (let index = 0; index < keys.length; index += 1) { const key = keys[index]; if (typeof key === 'string') (output as Record<string, unknown>)[key] = (value as Record<string, unknown>)[key]; } return ObjectFreeze(output); }
function sealedList<T>(value: readonly T[]): readonly T[] { const output: T[] = []; for (let index = 0; index < value.length; index += 1) output[index] = value[index]!; ObjectDefineProperty(output, 'toJSON', { value: null, enumerable: false, configurable: false, writable: false }); return ObjectFreeze(output); }
function bytes(value: ArrayLike<number>): Bytes { const output: number[] = []; for (let index = 0; index < value.length; index += 1) output[index] = value[index]!; return sealedList(output); }
function encode(value: string): Uint8Array { return ReflectApply(TextEncoderEncode, encoder, [value]) as Uint8Array; }
function append(target: number[], value: ArrayLike<number>): void { for (let index = 0; index < value.length; index += 1) target[target.length] = value[index]!; }
function denied(): DocumentSynthesisSourceSetDigestResult { return sealed({ status: 'denied' as const, code: 'input_invalid' as const, digestPayloadBytes: null, sourceSetDigestSha256: null }); }

function record(value: unknown, keys: readonly string[]): Record<string, unknown> | null { try { if (typeof value !== 'object' || value === null || ArrayIsArray(value) || IsProxy(value) || ObjectGetPrototypeOf(value) !== OBJECT) return null; const found = ReflectOwnKeys(value); if (found.length !== keys.length) return null; const copy = ObjectCreate(null) as Record<string, unknown>; for (let index = 0; index < keys.length; index += 1) { const key = keys[index]!; let present = false; for (let candidate = 0; candidate < found.length; candidate += 1) if (found[candidate] === key) present = true; if (!present) return null; const descriptor = ObjectGetOwnPropertyDescriptor(value, key); if (!descriptor || !descriptor.enumerable || !ObjectHasOwn(descriptor, 'value')) return null; copy[key] = descriptor.value; } return copy; } catch { return null; } }
function array(value: unknown): readonly unknown[] | null { try { if (!ArrayIsArray(value) || IsProxy(value) || ObjectGetPrototypeOf(value) !== ARRAY) return null; const descriptor = ObjectGetOwnPropertyDescriptor(value, 'length'); if (!descriptor || !ObjectHasOwn(descriptor, 'value') || typeof descriptor.value !== 'number' || !NumberIsSafeInteger(descriptor.value) || descriptor.value < 1 || descriptor.value > 32) return null; const found = ReflectOwnKeys(value); if (found.length !== descriptor.value + 1) return null; const copy: unknown[] = []; for (let index = 0; index < descriptor.value; index += 1) { const item = ObjectGetOwnPropertyDescriptor(value, `${index}`); if (!item || !item.enumerable || !ObjectHasOwn(item, 'value')) return null; copy[index] = item.value; } return copy; } catch { return null; } }
function raw32(value: unknown): Bytes | null { try { if (!ArrayIsArray(value) || IsProxy(value) || ObjectGetPrototypeOf(value) !== ARRAY) return null; const length = ObjectGetOwnPropertyDescriptor(value, 'length'); if (!length || !ObjectHasOwn(length, 'value') || length.value !== 32) return null; const found = ReflectOwnKeys(value); if (found.length !== 33 && found.length !== 34) return null; if (found.length === 34) { const toJSON = ObjectGetOwnPropertyDescriptor(value, 'toJSON'); if (!toJSON || toJSON.value !== null || toJSON.enumerable || toJSON.configurable || toJSON.writable) return null; } const copy: number[] = []; for (let index = 0; index < 32; index += 1) { const item = ObjectGetOwnPropertyDescriptor(value, `${index}`); if (!item || !item.enumerable || !ObjectHasOwn(item, 'value') || typeof item.value !== 'number' || !NumberIsSafeInteger(item.value) || item.value < 0 || item.value > 255) return null; copy[index] = item.value; } return bytes(copy); } catch { return null; } }
function integer(value: unknown): value is bigint { return typeof value === 'bigint' && value >= ZERO && value <= MAX_U64; }
function text(value: unknown): Uint8Array | null { if (typeof value !== 'string' || value.length === 0) return null; for (let index = 0; index < value.length; index += 1) { const code = ReflectApply(StringCharCodeAt, value, [index]) as number; if (code >= 0xd800 && code <= 0xdbff) { const next = index + 1 < value.length ? ReflectApply(StringCharCodeAt, value, [index + 1]) as number : -1; if (next < 0xdc00 || next > 0xdfff) return null; index += 1; } else if (code >= 0xdc00 && code <= 0xdfff) return null; else if (code <= 0x08 || code === 0x0b || code === 0x0c || (code >= 0x0e && code <= 0x1f) || code === 0x7f) return null; } const output = encode(value); return output.length > 0 && output.length <= 0xffff_ffff ? output : null; }
function parse(value: unknown, index: number): Parsed | null { const input = record(value, ['label', 'documentSourceRef', 'documentRevision', 'documentFreshnessEpoch', 'sourceByteLength', 'projectionDigestSha256']); if (!input || input.label !== `S${index + 1}` || !integer(input.documentRevision) || !integer(input.documentFreshnessEpoch) || typeof input.sourceByteLength !== 'number' || !NumberIsSafeInteger(input.sourceByteLength) || input.sourceByteLength < 1 || input.sourceByteLength > MAX_SOURCE_BYTES) return null; const label = text(input.label); const referenceBytes = text(input.documentSourceRef); const projectionDigestSha256 = raw32(input.projectionDigestSha256); if (!label || !referenceBytes || !projectionDigestSha256) return null; return { label: input.label, documentSourceRef: input.documentSourceRef as string, documentRevision: input.documentRevision, documentFreshnessEpoch: input.documentFreshnessEpoch, sourceByteLength: input.sourceByteLength, projectionDigestSha256, referenceBytes }; }
function compare(left: Parsed, right: Parsed): number { const length = left.referenceBytes.length < right.referenceBytes.length ? left.referenceBytes.length : right.referenceBytes.length; for (let index = 0; index < length; index += 1) if (left.referenceBytes[index] !== right.referenceBytes[index]) return left.referenceBytes[index]! - right.referenceBytes[index]!; return left.referenceBytes.length !== right.referenceBytes.length ? left.referenceBytes.length - right.referenceBytes.length : left.documentRevision < right.documentRevision ? -1 : left.documentRevision > right.documentRevision ? 1 : left.documentFreshnessEpoch < right.documentFreshnessEpoch ? -1 : left.documentFreshnessEpoch > right.documentFreshnessEpoch ? 1 : 0; }
function u32(value: number): number[] { return [(value >>> 24) & 255, (value >>> 16) & 255, (value >>> 8) & 255, value & 255]; }
function u64(value: bigint): number[] { const output: number[] = []; for (let index = 7; index >= 0; index -= 1) { output[index] = NumberConstructor(value & BYTE); value >>= SHIFT; } return output; }

/** Pure data-only codec; it neither resolves nor grants source-set authority. */
export function digestDocumentSynthesisSourceSet(value: unknown): DocumentSynthesisSourceSetDigestResult { try { const input = record(value, ['sources', 'sourceSetEpoch', 'revocationGeneration']); if (!input || !integer(input.sourceSetEpoch) || !integer(input.revocationGeneration)) return denied(); const sourceValues = array(input.sources); if (!sourceValues) return denied(); const sources: Parsed[] = []; let total = 0; for (let index = 0; index < sourceValues.length; index += 1) { const item = parse(sourceValues[index], index); if (!item || (index > 0 && compare(sources[index - 1]!, item) >= 0)) return denied(); total += item.sourceByteLength; if (total > MAX_SET_BYTES) return denied(); sources[index] = item; } const payload: number[] = []; const domain = encode(DOMAIN); append(payload, u32(domain.length)); append(payload, domain); append(payload, [0, 1, sources.length]); append(payload, u64(input.sourceSetEpoch)); append(payload, u64(input.revocationGeneration)); for (let index = 0; index < sources.length; index += 1) { const item = sources[index]!; const label = encode(item.label); append(payload, u32(label.length)); append(payload, label); append(payload, u32(item.referenceBytes.length)); append(payload, item.referenceBytes); append(payload, u64(item.documentRevision)); append(payload, u64(item.documentFreshnessEpoch)); append(payload, item.projectionDigestSha256); } const digestPayloadBytes = bytes(payload); const payloadBytes = new Uint8ArrayConstructor(digestPayloadBytes.length); for (let index = 0; index < digestPayloadBytes.length; index += 1) payloadBytes[index] = digestPayloadBytes[index]!; const sourceSetDigestSha256 = bytes(createHash('sha256').update(payloadBytes).digest()); return sealed({ status: 'available' as const, code: null, digestPayloadBytes, sourceSetDigestSha256 }); } catch { return denied(); } }
