#!/bin/bash
# Regenerate the universal Apple app Xcode project from project.yml (xcodegen),
# then run the network entitlement packaging guard. The pbxproj is committed but
# was previously generated by hand; wiring xcodegen here makes regeneration
# reproducible and prevents drift.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_DIR="$ROOT_DIR/native/MediFlowAppleApp"

if ! command -v xcodegen >/dev/null 2>&1; then
  echo "xcodegen not found. Install with: brew install xcodegen" >&2
  exit 1
fi

echo "Generating MediFlowAppleApp.xcodeproj from project.yml ..."
( cd "$PROJECT_DIR" && xcodegen generate --spec project.yml )

echo "Running structure guard ..."
"$ROOT_DIR/scripts/check-apple-structure.sh"

echo "Running network entitlement guard ..."
"$ROOT_DIR/scripts/check-apple-network-entitlements.sh"

echo "Apple Xcode project generated and verified."
